CREATE TABLE LOG_ERRORES (
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CODIGO_ERROR NUMBER,
    MENSAJE_ERROR VARCHAR2(500)
);

CREATE OR REPLACE PROCEDURE NUEVO_RESULTADO (e_LOCAL VARCHAR2, g_LOCAL INTEGER, e_VISITANTE VARCHAR2, g_VISITANTE NUMBER)
AS
    v_contador NUMBER;
    v_g_loc_ant INTEGER;
    v_g_vis_ant INTEGER;

    equipoNoExiste EXCEPTION;
    existePartido EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO v_contador 
    FROM EQUIPOS 
    WHERE EQUIPO IN (e_LOCAL, e_VISITANTE);

    IF v_contador < 2 THEN
        RAISE equipoNoExiste;
    END IF;

    v_contador := 0;

    SELECT COUNT(*) INTO v_contador
    FROM RESULTADOS
    WHERE EQUIPO_LOCAL = e_LOCAL AND EQUIPO_VISITANTE = e_VISITANTE;

    IF v_contador > 0 THEN
        -- Solo entramos aquí si sabemos que existe, así el SELECT no fallará
        SELECT GOLES_LOCAL, GOLES_VISITANTE 
        INTO v_g_loc_ant, v_g_vis_ant
        FROM RESULTADOS 
        WHERE EQUIPO_LOCAL = e_LOCAL AND EQUIPO_VISITANTE = e_VISITANTE;
        
        RAISE existePartido;
    END IF;

    INSERT INTO RESULTADOS(EQUIPO_LOCAL, GOLES_LOCAL, EQUIPO_VISITANTE, GOLES_VISITANTE)
    VALUES(e_LOCAL, g_LOCAL, e_VISITANTE, g_VISITANTE);

    IF g_LOCAL > g_VISITANTE THEN
        UPDATE CLASIFICACION SET GANADOS = GANADOS + 1, GOLES_FAVOR = GOLES_FAVOR + g_LOCAL, 
            GOLES_CONTRA = GOLES_CONTRA + g_VISITANTE, PUNTOS = PUNTOS + 3 WHERE EQUIPO = e_LOCAL;
        UPDATE CLASIFICACION SET PERDIDOS = PERDIDOS + 1, GOLES_FAVOR = GOLES_FAVOR + g_VISITANTE, 
            GOLES_CONTRA = GOLES_CONTRA + g_LOCAL WHERE EQUIPO = e_VISITANTE;
            
    ELSIF g_VISITANTE > g_LOCAL THEN 
        UPDATE CLASIFICACION SET GANADOS = GANADOS + 1, GOLES_FAVOR = GOLES_FAVOR + g_VISITANTE, 
            GOLES_CONTRA = GOLES_CONTRA + g_LOCAL, PUNTOS = PUNTOS + 3 WHERE EQUIPO = e_VISITANTE;
        UPDATE CLASIFICACION SET PERDIDOS = PERDIDOS + 1, GOLES_FAVOR = GOLES_FAVOR + g_LOCAL, 
            GOLES_CONTRA = GOLES_CONTRA + g_VISITANTE WHERE EQUIPO = e_LOCAL;
            
    ELSE
        UPDATE CLASIFICACION SET EMPATADOS = EMPATADOS + 1, GOLES_FAVOR = GOLES_FAVOR + g_LOCAL, 
            GOLES_CONTRA = GOLES_CONTRA + g_VISITANTE, PUNTOS = PUNTOS + 1 WHERE EQUIPO = e_LOCAL;
        UPDATE CLASIFICACION SET EMPATADOS = EMPATADOS + 1, GOLES_FAVOR = GOLES_FAVOR + g_VISITANTE, 
            GOLES_CONTRA = GOLES_CONTRA + g_LOCAL, PUNTOS = PUNTOS + 1 WHERE EQUIPO = e_VISITANTE;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Resultado registrado correctamente');
EXCEPTION
    WHEN equipoNoExiste THEN
        DBMS_OUTPUT.PUT_LINE('Alguno de los equipos no existe.');
    WHEN existePartido THEN
        DBMS_OUTPUT.PUT_LINE('Esos equipos ya han jugado ese partido. El resultado fue: ' || v_g_loc_ant || ' - ' || v_g_vis_ant);
    WHEN OTHERS THEN
        INSERT INTO LOG_ERRORES (CODIGO_ERROR, MENSAJE_ERROR) 
        VALUES (SQLCODE, SQLERRM);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Error inesperado registrado en LOG_ERRORES.');
END;

