DROP TABLE CLASIFICACION CASCADE CONSTRAINTS; 
DROP TABLE RESULTADOS CASCADE CONSTRAINTS;
DROP TABLE EQUIPOS CASCADE CONSTRAINTS;

CREATE TABLE EQUIPOS(
    EQUIPO VARCHAR2(10) PRIMARY KEY
);

CREATE TABLE RESULTADOS(
    EQUIPO_LOCAL VARCHAR2(10) REFERENCES EQUIPOS (EQUIPO),
    GOLES_LOCAL INTEGER,
    EQUIPO_VISITANTE VARCHAR2(10) REFERENCES EQUIPOS (EQUIPO),
    GOLES_VISITANTE INTEGER,
    PRIMARY KEY (EQUIPO_LOCAL, EQUIPO_VISITANTE)
);

CREATE TABLE CLASIFICACION(
    EQUIPO VARCHAR2(10) PRIMARY KEY REFERENCES EQUIPOS (EQUIPO),
    GANADOS INTEGER DEFAULT 0,
    EMPATADOS INTEGER DEFAULT 0,
    PERDIDOS INTEGER DEFAULT 0,
    GOLES_FAVOR INTEGER DEFAULT 0,
    GOLES_CONTRA INTEGER DEFAULT 0,
    PUNTOS INTEGER DEFAULT 0);

INSERT INTO EQUIPOS VALUES('EQUIPO A');
INSERT INTO EQUIPOS VALUES('EQUIPO B');
INSERT INTO EQUIPOS VALUES('EQUIPO C');
INSERT INTO EQUIPOS VALUES('EQUIPO D');
INSERT INTO EQUIPOS VALUES('EQUIPO E');
INSERT INTO EQUIPOS VALUES('EQUIPO F');
INSERT INTO EQUIPOS VALUES('EQUIPO G');
INSERT INTO EQUIPOS VALUES('EQUIPO H');
INSERT INTO EQUIPOS VALUES('EQUIPO I');
INSERT INTO EQUIPOS VALUES('EQUIPO J');

INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO A');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO B');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO C');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO D');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO E');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO F');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO G');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO H');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO I');
INSERT INTO CLASIFICACION (EQUIPO) VALUES ('EQUIPO J');

INSERT INTO RESULTADOS VALUES ('EQUIPO D',2,'EQUIPO J',2);
INSERT INTO RESULTADOS VALUES ('EQUIPO C',2,'EQUIPO B',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO H',2,'EQUIPO E',2);
INSERT INTO RESULTADOS VALUES ('EQUIPO I',1,'EQUIPO F',2);
INSERT INTO RESULTADOS VALUES ('EQUIPO G',3,'EQUIPO A',0);

INSERT INTO RESULTADOS VALUES ('EQUIPO F',2,'EQUIPO G',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO J',2,'EQUIPO A',1);
INSERT INTO RESULTADOS VALUES ('EQUIPO E',6,'EQUIPO I',0);
INSERT INTO RESULTADOS VALUES ('EQUIPO B',1,'EQUIPO H',0);
INSERT INTO RESULTADOS VALUES ('EQUIPO D',4,'EQUIPO C',1);

INSERT INTO RESULTADOS VALUES ('EQUIPO I',2,'EQUIPO B',6);
INSERT INTO RESULTADOS VALUES ('EQUIPO H',1,'EQUIPO D',2);
INSERT INTO RESULTADOS VALUES ('EQUIPO C',1,'EQUIPO J',6);
INSERT INTO RESULTADOS VALUES ('EQUIPO G',3,'EQUIPO E',1);
INSERT INTO RESULTADOS VALUES ('EQUIPO A',1,'EQUIPO F',4);

INSERT INTO RESULTADOS VALUES ('EQUIPO D',8,'EQUIPO I',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO E',4,'EQUIPO A',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO B',4,'EQUIPO G',6);
INSERT INTO RESULTADOS VALUES ('EQUIPO J',6,'EQUIPO F',2);
INSERT INTO RESULTADOS VALUES ('EQUIPO C',7,'EQUIPO H',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO F',1,'EQUIPO E',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO I',3,'EQUIPO C',5);
INSERT INTO RESULTADOS VALUES ('EQUIPO G',2,'EQUIPO D',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO A',2,'EQUIPO B',5);
INSERT INTO RESULTADOS VALUES ('EQUIPO H',5,'EQUIPO J',3);
INSERT INTO RESULTADOS VALUES ('EQUIPO J',2,'EQUIPO E',3);
INSERT INTO RESULTADOS VALUES ('EQUIPO B',6,'EQUIPO F',5);
INSERT INTO RESULTADOS VALUES ('EQUIPO D',1,'EQUIPO A',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO C',0,'EQUIPO G',0);
INSERT INTO RESULTADOS VALUES ('EQUIPO H',4,'EQUIPO I',1);
INSERT INTO RESULTADOS VALUES ('EQUIPO G',3,'EQUIPO H',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO I',0,'EQUIPO J',3);
INSERT INTO RESULTADOS VALUES ('EQUIPO A',1,'EQUIPO C',2);
INSERT INTO RESULTADOS VALUES ('EQUIPO F',2,'EQUIPO D',3);
INSERT INTO RESULTADOS VALUES ('EQUIPO E',3,'EQUIPO B',1);
INSERT INTO RESULTADOS VALUES ('EQUIPO C',6,'EQUIPO F',1);
INSERT INTO RESULTADOS VALUES ('EQUIPO D',2,'EQUIPO E',4);
INSERT INTO RESULTADOS VALUES ('EQUIPO J',2,'EQUIPO B',7);
INSERT INTO RESULTADOS VALUES ('EQUIPO H',3,'EQUIPO A',2);
INSERT INTO RESULTADOS VALUES ('EQUIPO I',0,'EQUIPO G',3);
INSERT INTO RESULTADOS VALUES ('EQUIPO E',6,'EQUIPO C',3);
INSERT INTO RESULTADOS VALUES ('EQUIPO A',10,'EQUIPO I',1);
INSERT INTO RESULTADOS VALUES ('EQUIPO F',0,'EQUIPO H',8);
INSERT INTO RESULTADOS VALUES ('EQUIPO G',2,'EQUIPO J',2);
INSERT INTO RESULTADOS VALUES ('EQUIPO B',3,'EQUIPO D',5);