CREATE USER Practica_EJ1_PLSQL IDENTIFIED BY Practica_EJ1_PLSQL;

GRANT CREATE SESSION TO Practica_EJ1_PLSQL WITH ADMIN OPTION;
GRANT CREATE TABLE TO Practica_EJ1_PLSQL WITH ADMIN OPTION;

/*ROLES*/
GRANT CREATE ROLE TO Practica_EJ1_PLSQL;
GRANT DROP ANY ROLE TO Practica_EJ1_PLSQL;
/*USUARIOS*/
GRANT CREATE USER TO Practica_EJ1_PLSQL;
GRANT DROP USER TO Practica_EJ1_PLSQL;

GRANT CREATE SEQUENCE TO Practica_EJ1_PLSQL;

ALTER USER Practica_EJ1_PLSQL QUOTA UNLIMITED ON USERS;