DROP USER admin01 CASCADE;
DROP USER medico01 CASCADE;
DROP USER recep01 CASCADE;

DROP ROLE ROL_ADMIN_CLINICO;
DROP ROLE ROL_PROFESIONAL_SANITARIO;
DROP ROLE ROL_RECEPCION;

CREATE ROLE ROL_ADMIN_CLINICO;
CREATE ROLE ROL_PROFESIONAL_SANITARIO;
CREATE ROLE ROL_RECEPCION;

GRANT CREATE SESSION TO ROL_ADMIN_CLINICO;
GRANT CREATE SESSION TO ROL_PROFESIONAL_SANITARIO;
GRANT CREATE SESSION TO ROL_RECEPCION;

GRANT SELECT, INSERT, UPDATE, DELETE ON PACIENTE TO ROL_ADMIN_CLINICO;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROFESIONAL TO ROL_ADMIN_CLINICO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSULTA TO ROL_ADMIN_CLINICO;
GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICIO_CLINICO TO ROL_ADMIN_CLINICO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CITA TO ROL_ADMIN_CLINICO;
GRANT SELECT, INSERT, UPDATE, DELETE ON RESULTADO_SERVICIO TO ROL_ADMIN_CLINICO;

GRANT SELECT ON PACIENTE TO ROL_PROFESIONAL_SANITARIO;
GRANT SELECT ON CITA TO ROL_PROFESIONAL_SANITARIO;
GRANT SELECT, INSERT, UPDATE ON RESULTADO_SERVICIO TO ROL_PROFESIONAL_SANITARIO;

GRANT SELECT, INSERT, UPDATE ON PACIENTE TO ROL_RECEPCION;
GRANT SELECT ON PROFESIONAL TO ROL_RECEPCION;
GRANT SELECT ON CONSULTA TO ROL_RECEPCION;
GRANT SELECT ON SERVICIO_CLINICO TO ROL_RECEPCION;
GRANT SELECT, INSERT, UPDATE ON CITA TO ROL_RECEPCION;

CREATE USER admin01 IDENTIFIED BY admin01;
CREATE USER medico01 IDENTIFIED BY medico01;
CREATE USER recep01 IDENTIFIED BY recep01;

GRANT ROL_ADMIN_CLINICO TO admin01;
GRANT ROL_PROFESIONAL_SANITARIO TO medico01;
GRANT ROL_RECEPCION TO recep01;
