DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP TABLE PROFESIONAL CASCADE CONSTRAINTS;
DROP TABLE CONSULTA CASCADE CONSTRAINTS;
DROP TABLE SERVICIO_CLINICO CASCADE CONSTRAINTS;
DROP TABLE CITA CASCADE CONSTRAINTS;
DROP TABLE RESULTADO_SERVICIO CASCADE CONSTRAINTS;

CREATE TABLE PACIENTE(
    ID_PACIENTE VARCHAR2(9),
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(100),
    APELLIDOS VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    TELEFONO NUMBER(9),
    EMAIL VARCHAR2(100),
    CONSTRAINT PACIENTE_ID_PK PRIMARY KEY (ID_PACIENTE)
);

CREATE TABLE PROFESIONAL(
    ID_PROFESIONAL VARCHAR2(9),
    NOMBRE VARCHAR2(100),
    APELLIDOS VARCHAR2(100),
    ESPECIALIDAD VARCHAR2(20),
    COLEGIADO NUMBER(10) UNIQUE,
    CONSTRAINT PROFESIONAÑ_ID_PK PRIMARY KEY (ID_PROFESIONAL)
);

CREATE TABLE CONSULTA(
    ID_CONSULTA VARCHAR2(9),
    PLANTA NUMBER(10),
    NUMERO NUMBER(10),
    TIPO VARCHAR2(20),
    CONSTRAINT CONSULTA_ID_PK PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT TIPO_CH CHECK (TIPO IN ('GENERAL', 'ESPECIALISTA'))
);

CREATE TABLE SERVICIO_CLINICO (
    ID_SERVICIO VARCHAR2(9),
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(100),
    REQUIERE_AYUNO VARCHAR2(2),
    CONSTRAINT SERVICIO_ID_PK PRIMARY KEY (ID_SERVICIO),
    CONSTRAINT AYUNA_REQUIERE_CH CHECK (REQUIERE_AYUNO IN('SI','NO'))
);

CREATE TABLE CITA (
    ID_CITA VARCHAR2(9),
    ID_PACIENTE VARCHAR2(9),
    ID_PROFESIONAL VARCHAR2(9),
    ID_CONSULTA VARCHAR2(9),
    ID_SERVICIO VARCHAR2(9),
    FECHA_HORA DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(10),
    CONSTRAINT CITA_ID_PK PRIMARY KEY (ID_CITA),
    CONSTRAINT PACIENTE_ID_FK FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE,
    CONSTRAINT PROFESIONAL_ID_FK FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONAL,
    CONSTRAINT CONSULTA_ID_FK FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA,
    CONSTRAINT SERVICIO_ID_FK FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO_CLINICO,
    CONSTRAINT ESTADO_CH CHECK (ESTADO IN('PENDIENTE','REALIZADA','CANCELADA'))
);

CREATE TABLE RESULTADO_SERVICIO(
    ID_RESULTADO VARCHAR2(9),
    ID_CITA VARCHAR2(9),
    ID_SERVICIO VARCHAR2(9),
    FECHA_REALIZACION DATE,
    INFORME CLOB,
    CONSTRAINT RESULTADO_ID_PK PRIMARY KEY (ID_RESULTADO),
    CONSTRAINT SERVICIO_ID2_FK FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO_CLINICO,
    CONSTRAINT CITA_ID_FK FOREIGN KEY (ID_CITA) REFERENCES CITA
);