CREATE USER PrSGCSG IDENTIFIED BY PrSGCSG;

GRANT CREATE SESSION TO PrSGCSG WITH ADMIN OPTION;
GRANT CREATE TABLE TO PrSGCSG WITH ADMIN OPTION;

GRANT CREATE ROLE TO PrSGCSG;
GRANT DROP ANY ROLE TO PrSGCSG;

GRANT CREATE USER TO PrSGCSG;
GRANT DROP USER TO PrSGCSG;

ALTER USER PrSGCSG QUOTA UNLIMITED ON USER;

ALTER TABLE PROFESIONAL
MODIFY COLEGIADO NUMBER(10) NOT NULL
MODIFY ESPECIALIDAD VARCHAR2(400);

ALTER TABLE RESULTADO_SERVICIO
ADD ID_PROFESIONAL VARCHAR2(9)
ADD CONSTRAINT PROFESIONAL_ID2_FK FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONAL;

ALTER TABLE CITA
DROP CONSTRAINT ESTADO_CH
ADD CONSTRAINT ESTADO_CH CHECK (ESTADO IN('PENDIENTE','REALIZADA','CANCELADA','REPROGRAMADA'));