--1.Número total de clientes.
SELECT COUNT(*)
FROM CLIENTES;

--2.Número total de mascotas.
SELECT COUNT(*)
FROM MASCOTAS;

--3.Número total de citas.
SELECT COUNT(*)
FROM CITAS;

--4.Número de pagos realizados.
SELECT COUNT(*)
FROM PAGOS;

--5.Número de citas sin pago.
SELECT COUNT(*)
FROM MASCOTAS M JOIN PAGOS P ON M.ID_CLIENTE=P.ID_CLIENTE AND M.ID_MASCOTA = P.ID_MASCOTA AND M.FECHA_CITA = P.FECHA_CITA
WHERE IMPORTE IS NULL;

SELECT COUNT(*)
FROM (SELECT ID_CLIENTE, ID_MASCOTA, FECHA_CITA
    FROM MASCOTAS
    MINUS
    SELECT ID_CLIENTE, ID_MASCOTA, FECHA_CITA
    FROM PAGOS
);

SELECT COUNT(C.FEFECHA_CITA) AS CITAS_SIN_PAGO
FROM CITAS C LEFT JOIN PAGOS P ON C.FECHA_CITA = P.FECHA_CITA AND C.ID_MASCOTA = P.ID_MASCOTA AND C.ID_CLIENTE = P.ID_CLIENTE
WHERE FECHA_PAGO IS NULL;
--6.Número de mascotas por especie.
SELECT ESPECIE, COUNT(*) AS NUMERO_MASCOTAS
FROM MASCOTAS
GROUP BY ESPECIE;

--7.Número de mascotas por cliente.
SELECT C.NOMBRE, COUNT(M.ID_MASCOTA) AS NUMERO_MASCOTAS
FROM CLIENTES C JOIN MASCOTAS M ON C.ID_CLIENTE = M.ID_CLIENTE
GROUP BY C.NOMBRE;

--8.Número de citas por cliente.
SELECT CLI.NOMBRE, COUNT(C.FECHA_CITA) AS NUMERO_CITAS
FROM CLIENTES CLI JOIN CITAS C ON C.ID_CLIENTE = CLI.ID_CLIENTE
GROUP BY CLI.NOMBRE;


--9.Número de citas por mascota.
SELECT M.NOMBRE, COUNT(C.FECHA_CITA) AS NUMERO_CITAS
FROM MASCOTAS M JOIN CITAS C ON M.ID_CLIENTE = C.ID_CLIENTE AND M.ID_MASCOTA = C.ID_MASCOTA
GROUP BY M.NOMBRE;

--10.Número de atenciones por cita.PrácticaClínicaVeterinaria
SELECT M.NOMBRE AS MASCOTA, A.FECHA_CITA, COUNT(A.ID_PERSONAL) AS TOTAL_ATENCIONES
FROM MASCOTAS M JOIN ATENCIONES A ON M.ID_CLIENTE = A.ID_CLIENTE AND M.ID_MASCOTA = A.ID_MASCOTA
GROUP BY M.NOMBRE, A.ID_CLIENTE, A.ID_MASCOTA, A.FECHA_CITA
ORDER BY A.FECHA_CITA;

--11.Clientes que tienen más de una mascota.
SELECT C.ID_CLIENTE, C.NOMBRE AS CLIENTE, COUNT(M.ID_MASCOTA) AS N_MASCOTAS
FROM CLIENTES C JOIN MASCOTAS M ON C.ID_CLIENTE = M.ID_CLIENTE
GROUP BY C.ID_CLIENTE, C.NOMBRE HAVING COUNT(M.ID_MASCOTA) > 1;

--12.Mascotas que han tenido más de una cita.
SELECT M.ID_MASCOTA, CLI.ID_CLIENTE, M.NOMBRE AS MASCOTA, COUNT(C.FECHA_CITA) AS NUMERO_CITAS
FROM MASCOTAS M JOIN CITAS C ON M.ID_CLIENTE = C.ID_CLIENTE AND M.ID_MASCOTA = C.ID_MASCOTA
JOIN CLIENTES CLI ON M.ID_CLIENTE = CLI.ID_CLIENTE
GROUP BY M.ID_MASCOTA, CLI.ID_CLIENTE, M.NOMBRE HAVING COUNT(C.FECHA_CITA) > 1;

--13.Fechas de cita en las que hubo más de una atención.
SELECT C.FECHA_CITA, COUNT(A.ID_PERSONAL)
FROM CITAS C JOIN ATENCIONES A ON C.ID_CLIENTE = A.ID_CLIENTE AND C.ID_MASCOTA = A.ID_MASCOTA AND C.FECHA_CITA = A.FECHA_CITA
GROUP BY FECHA_CITA HAVING COUNT(A.ID_PERSONAL) > 1;

--14.Clientes cuyo importe total pagado supera los 50 €.
SELECT CLI.ID_CLIENTE, CLI.NOMBRE, SUM(P.IMPORTE) AS IMPORTE_TOTAL
FROM CLIENTES CLI JOIN PAGOS P ON CLI.ID_CLIENTE = P.ID_CLIENTE
GROUP BY CLI.ID_CLIENTE, CLI.NOMBRE HAVING SUM(P.IMPORTE) > 50;

--15.Veterinarios que han atendido más de una cita.
SELECT PE.ID_PERSONAL, PE.NOMBRE, COUNT(DISTINCT A.FECHA_CITA)
FROM PERSONAL PE JOIN ATENCIONES A ON PE.ID_PERSONAL = A.ID_PERSONAL
GROUP BY PE.ID_PERSONAL, PE.NOMBRE HAVING COUNT(DISTINCT A.FECHA_CITA) > 1;

SELECT PE.NOMBRE, COUNT(*) AS NUMERO_ATENCIONES
FROM PERSONAL PE JOIN ATENCIONES A ON PE.ID_PERSONAL = A.ID_PERSONAL AND PE.ROL = 'Veterinario'
GROUP BY PE.NOMBRE
HAVING COUNT(*)>1;

--16.Importe total cobrado por la clínica.
SELECT SUM(P.IMPORTE) || '€' AS IMPORTE_TOTAL
FROM PAGOS P;

--17.Importe medio de las citas pagadas.
SELECT AVG(P.IMPORTE) || '€' AS IMPORTE_MEDIO
FROM PAGOS P;

SELECT SUM(P.IMPORTE)/COUNT(P.IMPORTE) AS IMPORTE_MEDIO
FROM PAGOS P;

--18.Importe máximo y mínimo de una cita.
SELECT MAX(P.IMPORTE) AS IMPORTE_MAX, MIN(P.IMPORTE) AS IMPORTE_MIN
FROM PAGOS P;

--19.Importe total pagado por cliente.
SELECT CLI.ID_CLIENTE, CLI.NOMBRE, SUM(P.IMPORTE)
FROM CLIENTES CLI JOIN PAGOS P ON CLI.ID_CLIENTE = P.ID_CLIENTE
GROUP BY CLI.ID_CLIENTE, CLI.NOMBRE;

--20.Importe total pagado por mascota.
SELECT M.ID_MASCOTA, M.NOMBRE, SUM(P.IMPORTE)
FROM MASCOTAS M JOIN PAGOS P ON M.ID_MASCOTA = P.ID_MASCOTA AND M.ID_CLIENTE = P.ID_CLIENTE
GROUP BY M.ID_MASCOTA, M.NOMBRE;

--21.Listar todos los nombres de personas (clientes + personal) sin repetir.
SELECT DISTINCT CLI.NOMBRE AS NOMBRE_CLIENTE
FROM CLIENTES CLI
UNION
SELECT DISTINCT PE.NOMBRE AS NOMBRE_PERSONAL
FROM PERSONAL PE;

--22.Lo mismo, pero permitiendo repetidos.
SELECT CLI.NOMBRE AS NOMBRE_CLIENTE
FROM CLIENTES CLI
UNION ALL
SELECT PE.NOMBRE AS NOMBRE_PERSONAL
FROM PERSONAL PE;

--23.Clientes que también aparecen como personal
--(ahora no hay, pero sirve para entender el operador).
SELECT NOMBRE FROM CLIENTES
INTERSECT
SELECT NOMBRE FROM PERSONAL;

--24.Clientes que no tienen ninguna cita.
SELECT ID_CLIENTE FROM CLIENTES
MINUS
SELECT ID_CLIENTE FROM CITAS;

--25.Mascotas que no tienen pago asociado. 
--¿Podrías hacer la consulta de tal forma que supiéramos el nombre de la mascota y de su cliente?
SELECT ID_CLIENTE, ID_MASCOTA, FECHA_CITA FROM CITAS
MINUS
SELECT ID_CLIENTE, ID_MASCOTA, FECHA_CITA FROM PAGOS;

--26.Para cada cliente, mostrar:
--número de mascotas
--número de citas
--importe total pagado
SELECT CLI.ID_CLIENTE, COUNT(DISTINCT M.ID_MASCOTA) AS NUMERO_MASCOTAS, COUNT(DISTINCT C.FECHA_CITA) AS NUMERO_CITAS,
NVL(SUM(P.IMPORTE),0) AS TOTAL_PAGADO
FROM CLIENTES CLI LEFT JOIN MASCOTAS M ON CLI.ID_CLIENTE = M.ID_CLIENTE LEFT JOIN CITAS C ON C.ID_CLIENTE = CLI.ID_CLIENTE
GROUP BY C.ID_CLIENTE;

--27.Mostrar la mascota con mayor gasto acumulado.
SELECT M.NOMBRE
FROM MASCOTAS M JOIN PAGOS P ON M.ID_CLIENTE = P.ID_CLIENTE AND M.ID_MASCOTA = P.ID_MASCOTA
GROUP BY M.NOMBRE HAVING SUM(IMPORTE) = (SELECT MAX(SUM(IMPORTE)) 
                                        FROM PAGOS 
                                        GROUP BY ID_CLIENTE, ID_MASCOTA);

--28.Mostrar el cliente con más citas.
SELECT CLI.NOMBRE
FROM CITAS C JOIN CLIENTES CLI ON C.ID_CLIENTE = CLI.ID_CLIENTE
GROUP BY CLI.NOMBRE 
HAVING COUNT(*) = (
    SELECT MAX(CONT(*))
    FROM CITAS
    GROUP BY ID_CLIENTE
);

--29.Mostrar qué veterinario ha realizado más atenciones.
SELECT P.NOMBRE
FROM PERSONAL P JOIN ATENCIONES A ON P.ID_CLIENTE = A.ID_CLIENTE
GROUP BY P.NOMBRE
HAVING COUNT(*) = (
    SELECT MAX(CONT(*))
    FROM ATENCIONES
    GROUP BY ID_PERSONAL
);
