CREATE TABLE DEPART (
  DEPT_NO NUMBER(2) PRIMARY KEY,
  DNOMBRE VARCHAR2(20),
  LOC VARCHAR2(20)
);

CREATE TABLE EMPLE (
  EMP_NO NUMBER(4) PRIMARY KEY,
  APELLIDO VARCHAR2(20),
  OFICIO VARCHAR2(15),
  DIR NUMBER(4),
  FECHA_ALT DATE,
  SALARIO NUMBER(7,2),
  COMISION NUMBER(7,2),
  DEPT_NO NUMBER(2)
);

INSERT INTO DEPART VALUES (10, 'CONTABILIDAD', 'SEVILLA');
INSERT INTO DEPART VALUES (20, 'INVESTIGACION', 'MADRID');
INSERT INTO DEPART VALUES (30, 'VENTAS', 'BARCELONA');

INSERT INTO EMPLE VALUES (7369, 'SANCHEZ', 'EMPLEADO', 7902, SYSDATE, 1200, NULL, 20);
INSERT INTO EMPLE VALUES (7499, 'ARROYO', 'VENDEDOR', 7698, SYSDATE, 1500, 300, 30);
INSERT INTO EMPLE VALUES (7521, 'SALA', 'VENDEDOR', 7698, SYSDATE, 1600, 500, 30);
INSERT INTO EMPLE VALUES (7566, 'JIMENEZ', 'DIRECTOR', 7839, SYSDATE, 3000, NULL, 20);
INSERT INTO EMPLE VALUES (7839, 'REY', 'PRESIDENTE', NULL, SYSDATE, 5000, NULL, 10);

ALTER TABLE EMPLE
ADD CONSTRAINT EMPLE_DPTO_FK FOREIGN KEY (DEPT_NO) REFERENCES DEPART;
