<!ELEMENT hardwareCatalog (item+)>

<!-- Cada producto tiene: nombreProducto, descripcion, precio y caracteristicas -->
<!ELEMENT item (id,type,brand,model,specifications)>

<!-- Elementos de texto -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!-- Precio con texto y un atributo moneda -->
<!ELEMENT brand (#PCDATA)>


<!-- Conjunto de características -->
<!ELEMENT model (#PCDATA)>

<!-- Cada caracteristica está vacía y se define solo con atributos -->
<!ELEMENT specifications (#PCDATA)>
