/*
CREATE USER PR1MANIPULACION IDENTIFIED BY PR1MANIPULACION;
GRANT CREATE SESSION TO PR1MANIPULACION;
GRANT CREATE TABLE TO PR1MANIPULACION;
GRANT CREATE SEQUENCE TO PR1MANIPULACION;
ALTER USER PR1MANIPULACION QUOTA UNLIMITED ON USERS;
*/
DROP TABLE PRODUCTOS CASCADE CONSTRAINT;
DROP TABLE PRODUCTOSBACKUP CASCADE CONSTRAINT;

-- Tabla principal de productos
CREATE TABLE Productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    categoria VARCHAR2(30) NOT NULL,
    precio NUMBER(7,2) NOT NULL,
    stock NUMBER(5) DEFAULT 0
);

-- Tabla de respaldo o para operaciones con SELECT
CREATE TABLE ProductosBackup (
    id_producto NUMBER,
    nombre VARCHAR2(50),
    categoria VARCHAR2(30),
    precio NUMBER(7,2),
    stock NUMBER(5)
);

INSERT INTO Productos (nombre, categoria, precio, stock) VALUES ('Laptop Lenovo', 'Electrónica', 850.00, 10);
INSERT INTO Productos (nombre, categoria, precio, stock) VALUES ('Smartphone Samsung', 'Electrónica', 650.00, 15);
INSERT INTO Productos (nombre, categoria, precio, stock) VALUES ('Camiseta Adidas', 'Ropa', 30.00, 50);
INSERT INTO Productos (nombre, categoria, precio, stock) VALUES ('Zapatos Nike', 'Ropa', 80.00, 25);
INSERT INTO Productos (nombre, categoria, precio, stock) VALUES ('Cafetera DeLonghi', 'Hogar', 120.00, 8);