--1--
SELECT NOMBRE AS ALUMNOS_REPETIDORES, FECHA_NACIMIENTO
FROM ALUMNOS
WHERE REPETIDOR = 'S'
ORDER BY FECHA_NACIMIENTO;

--2--
SELECT NOMBRE AS ALUMNOS, DECODE(REPETIDOR, 'S', 'Es repetidor','N','No es repetidor') AS REPETIDOR, FECHA_NACIMIENTO
FROM ALUMNOS
ORDER BY FECHA_NACIMIENTO;

--3--
SELECT A.NOMBRE AS ALUMNO, CE.ID_CE AS CE, CE.DESCRIPCION AS DESCRIPCION, C.NOTA
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE AND C.ID_RA = CE.ID_RA
WHERE C.ID_PRUEBA = 1 AND C.ID_RA = 1
ORDER BY A.NOMBRE, CE.ID_CE;

--4--
SELECT A.NOMBRE AS ALUMNO, AVG(C.NOTA) AS NOTA_MEDIA_RA6
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
WHERE C.ID_PRUEBA = 2 AND C.ID_RA = 6
GROUP BY A.NOMBRE
ORDER BY AVG(C.NOTA) DESC;

--5--
SELECT RA.CODIGO AS RA, RA.DESCRIPCION AS RA_DESCRIPCION, NVL(P.NOMBRE, 'No existe prueba') AS NOMBRE_PRUEBA, NVL(P.TIPO, 'No existe prueba') AS TIPO_PRUEBA
FROM RESULTADOS_APRENDIZAJE RA
LEFT JOIN PRUEBAS_CRITERIOS PC ON RA.ID_RA = PC.ID_RA
LEFT JOIN PRUEBAS_EVALUACION P ON PC.ID_PRUEBA = P.ID_PRUEBA;

--6--
SELECT RA.CODIGO AS RA, NVL(P.NOMBRE, 'No se ha hecho prueba aún') AS PRUEBA
FROM RESULTADOS_APRENDIZAJE RA
LEFT JOIN PRUEBAS_CRITERIOS PC ON RA.ID_RA = PC.ID_RA
LEFT JOIN PRUEBAS_EVALUACION P ON PC.ID_PRUEBA = P.ID_PRUEBA
WHERE P.NOMBRE IS NULL;

--7--
FROM RA.ID_RA AS RA, AVG(C.NOTA) AS NOTA_MEDIA
FROM CALIFICACIONES C JOIN RESULTADOS_APRENDIZAJE RA ON C.ID_RA = RA.ID_RA
GROUP BY RA.ID_RA
ORDER BY AVG(C.NOTA) DESC;

--8--
SELECT A.NOMBRE AS ALUMNO, MAX(C.NOTA) AS NOTA_MAXIMA, MIN(C.NOTA) AS NOTA_MINIMA
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
WHERE C.ID_PRUEBA = 4
GROUP BY A.NOMBRE;

--9--
SELECT A.NOMBRE AS ALUMNO, AVG(C.NOTA) AS NOTA_MEDIA_PRUEBA3
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
WHERE C.ID_PRUEBA = 3
GROUP BY A.NOMBRE HAVING AVG(C.NOTA) > (SELECT AVG(NOTA)
                                            FROM CALIFICACIONES
                                            WHERE ID_PRUEBA = 3);

--10--
SELECT A.NOMBRE AS ALUMNO, P.NOMBRE AS PRUEBA, P.TIPO AS TIPO_PRUEBA, RA.CODIGO AS RA, CE.ID_CE AS CE, C.NOTA AS NOTA
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN PRUEBAS_EVALUACION P ON C.ID_PRUEBA = P.ID_PRUEBA
JOIN RESULTADOS_APRENDIZAJE RA ON C.ID_RA = RA.ID_RA
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE AND C.ID_RA = CE.ID_RA
WHERE NOTA < (SELECT AVG(NOTA)
            FROM CALIFICACIONES
            WHERE ID_PRUEBA = C.ID_PRUEBA);

--11--
SELECT A.NOMBRE AS ALUMNO, TRUNC(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) || ' años' AS EDAD
FROM ALUMNOS;

--13--
CREATE VIEW V_ALUMNOS_APROBADOS_RA
AS
SELECT A.ID_ALUMNO, A.NOMBRE AS ALUMNO, RA.ID_RA AS ID_RA, RA.CODIGO AS RA_CODIGO, AVG(C.NOTA) AS NOTA_PROMEDIO
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN RESULTADOS_APRENDIZAJE RA ON C.ID_RA = RA.ID_RA
GROUP BY A.ID_ALUMNO, A.NOMBRE, RA.ID_RA, RA.CODIGO HAVING AVG(C.NOTA)>=5;