--Mostrar el nombre en mayúsculas y el dominio del email:
SELECT UPPER(NOMBRE) NOMBRE, SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)
FROM USUARIOS;

--Listar usuarios cuyo email no termina en .com.
SELECT UPPER(NOMBRE) AS NOMBRE, SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) AS MAIL
FROM USUARIOS
WHERE SUBSTR(EMAIL,INSTR(EMAIL,'.')) != '.com';

SELECT NOMBRE, EMAIL
FROM USUARIOS U
WHERE NOT EXISTS (SELECT EMAIL
                    FROM USUARIOS
                    WHERE UPPER(EMAIL) LIKE '%.COM' AND U.EMAIL = EMAIL);

SELECT NOMBRE, EMAIL
FROM USUARIOS U
WHERE EMAIL NOT LIKE'%.COM';

--Mostrar nombre, fecha de alta y:
    --año de alta
    --mes de alta
SELECT NOMBRE, FECHA_ALTA, EXTRACT(YEAR FROM FECHA_ALTA) AÑO, EXTRACT(MONTH FROM FECHA_ALTA) MES
FROM USUARIOS;

--Mostrar los usuarios que llevan más de 2 años registrados.
SELECT NOMBRE, ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_ALTA)/12) AS AÑOS_REGISTRADOS
FROM USUARIOS
WHERE MONTHS_BETWEEN(SYSDATE, FECHA_ALTA) > 24;

--Mostrar cada pedido con:

    --importe original
    --importe redondeado a 2 decimales
    --importe truncado
SELECT IMPORTE AS IMPORTE_ORIGINAL, ROUND(IMPORTE,2) AS IMPORTE_REDONDEADO,TRUNC(IMPORTE) AS IMPORTE_TRUNCADO
FROM PEDIDOS
WHERE IMPORTE IS NOT NULL;

--Mostrar el importe con formato moneda:
SELECT TO_CHAR(IMPORTE, '999G999D999L') AS IMPORTE_MONEDA
FROM PEDIDOS;

--Mostrar todos los usuarios, tengan o no pedidos:
    --Si no tienen pedidos → mostrar "SIN PEDIDOS"
SELECT NOMBRE, NVL(TO_CHAR(ID_PEDIDO), 'SIN PEDIDOS')
FROM USUARIOS U LEFT JOIN PEDIDOS P ON U.ID_USUARIO = P.ID_USUARIO;

SELECT NOMBRE,
CASE
    WHEN ID_PEDIDO IS NULL THEN 'SIN PEDIDOS'
    ELSE TO_CHAR(ID_PEDIDO)
    END AS ID_PEDIDO
FROM USUARIOS U LEFT JOIN PEDIDOS P ON U.ID_USUARIO = P.ID_USUARIO;

--Mostrar el estado del pedido con texto amigable:
    --'P'->'Pendiente',
    --'E'->'Enviado',
    --'C'->'Cancelado',
    --otra cosa ->'Desconocido'
SELECT NOMBRE, FECHA_PEDIDO, IMPORTE, DECODE (ESTADO, 'P','Pendiente','C','Cancelado','E','Enviado','NO HAY PEDIDOS') AS ESTADO_PEDIDO
FROM USUARIOS U JOIN PEDIDOS P ON U.ID_USUARIO = P.ID_USUARIO;

SELECT NOMBRE, FECHA_PEDIDO, IMPORTE
CASE
    WHEN ESTADO = 'P' THEN 'Pendiente
    WHEN ESTADO = 'P' THEN 'Pendiente
    WHEN ESTADO = 'P' THEN 'Pendiente
    WHEN ESTADO = 'P' THEN 'Pendiente
--(...)

--Mostrar los usuarios que han realizado algún pedido con importe mayor que la media individual de sus pedidos
SELECT DISTINCT U.ID_USUARIO, U.NOMBRE
FROM USUARIOS U
JOIN PEDIDOS P ON P.ID_USUARIO = U.ID_USUARIO
WHERE P.IMPORTE > (
    SELECT AVG(P2.IMPORTE)
    FROM PEDIDOS P2
    WHERE P2.ID_USUARIO = P.ID_USUARIO
);

--Mostrar pedidos realizados el mismo mes y año que el registro del usuario.
SELECT ID_PEDIDO, FECHA_PEDIDO, IMPORTE, NOMBRE, FECHA_ALTA
FROM USUARIOS U
JOIN PEDIDOS P ON U.ID_USUARIO = P.ID_USUARIO
WHERE TO_CHAR

SELECT ID_PEDIDO, FECHA_PEDIDO, IMPORTE, NOMBRE, FECHA_ALTA
FROM USUARIOS U
JOIN PEDIDOS P ON U.ID_USUARIO = P.ID_USUARIO
WHERE EXTRACT(YEAR FROM FECHA_PEDIDO) = EXTRACT(YEAR FROM FECHA_ALTA)
AND EXTRACT(MONTH FROM FECHA_PEDIDO) = EXTRACT(MONTH FROM FECHA_ALTA);

--usuarios sin pedidos
SELECT NOMBRE, EMAIL, FECHA_ALTA
FROM USUARIOS U LEFT JOIN PEDIDOS P ON U.ID_USUARIO = P.ID_USUARIO
WHERE ID_PEDIDO IS NULL;

--pedidos con importe null
SELECT NOMBRE, EMAIL, FECHA_ALTA, IMPORTE, FECHA_PEDIDO
FROM USUARIOS U JOIN PEDIDOS P ON U.ID_USUARIO = P.ID_USUARIO
WHERE IMPORTE IS NULL;

--edad aproximada
SELECT NOMBRE, ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NAC)/12) || 'AÑOS' AS EDAD
FROM USUARIOS;

--dominio del email
SELECT NOMBRE, SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)
FROM USUARIOS;

--usuarios con más de X años registrados
SELECT NOMBRE,FECHA_ALTA, TRUNC(MONTHS_BETWEEN(SYSDATE,FECHA_ALTA)/12) AS AÑOS_REGISTRADOS
FROM USUARIOS
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE,FECHA_ALTA)/12) >1;

