/*
1Mostrar todas las mascotas con el nombre de su dueño
*/
SELECT M.NOMBRE MASCOTA, C.NOMBRE Clientes
FROM MASCOTAS M JOIN CLIENTES C ON M.ID_CLIENTE = C.ID_CLIENTE;

SELECT M.NOMBRE MASCOTA,ESPECIE,C.NOMBRE Clientes
FROM MASCOTAS M JOIN CLIENTES C ON M.ID_CLIENTE = C.ID_CLIENTE
ORDER BY ESPECIE;

--Listar las citas indicando nombre de la mascota y del cliente
SELECT C.FECHA_CITA, M.NOMBRE MASCOTA, CL.NOMBRE CLIENTES
FROM CITAS C JOIN MASCOTAS M ON C.ID_CLIENTE = M.ID_CLIENTE AND C.ID_MASCOTA = M.ID_MASCOTA
JOIN CLIENTES CL ON C.ID_CLIENTE = CL.ID_CLIENTE
ORDER BY FECHA_CITA;

--Mostrar el personal que trabaja en la clínica
SELECT *
FROM PERSONAL;

--Mostrar las citas de una mascota concreta (Luna)
SELECT C.FECHA_CITA, C.MOTIVO, M.NOMBRE MASCOTA
FROM CITAS C JOIN MASCOTAS M ON C.ID_CLIENTE = M.ID_CLIENTE AND C.ID_MASCOTA = M.ID_MASCOTA
WHERE UPPER(M.NOMBRE) = 'LUNA';

--Mostrar las citas con su diagnóstico (si lo tienen)
SELECT C.FECHA_CITA, M.NOMBRE MASCOTA, D.DESCRIPCION
FROM CITAS C JOIN MASCOTAS M ON C.ID_CLIENTE = M.ID_CLIENTE AND C.ID_MASCOTA = M.ID_MASCOTA
JOIN DIAGNOSTICOS D ON C.ID_CLIENTE = D.ID_CLIENTE AND C.ID_MASCOTA = D.ID_MASCOTA AND C.FECHA_CITA = D.FECHA_CITA;

--Mostrar las atenciones indicando quién atendió a cada mascota
SELECT M.NOMBRE MASCOTA, A.OBSERVACIONES, P.NOMBRE ATENDIDO
FROM ATENCIONES A JOIN MASCOTAS M ON M.ID_MASCOTA = A.ID_MASCOTA AND M.ID_CLIENTE = A.ID_CLIENTE
JOIN PERSONAL P ON P.ID_PERSONAL = A.ID_PERSONAL;

--Mostrar las recomendaciones dadas en cada cita
SELECT C.ID_CLIENTE, C.ID_MASCOTA, C.FECHA_CITA, R.TEXTO
FROM CITAS C JOIN RECOMENDACIONES R ON C.ID_CLIENTE = R.ID_CLIENTE AND C.ID_MASCOTA = R.ID_MASCOTA AND C.FECHA_CITA = R.FECHA_CITA;

SELECT C.ID_CLIENTE, C.ID_MASCOTA,M.NOMBRE, C.FECHA_CITA, R.TEXTO
FROM CITAS C JOIN RECOMENDACIONES R ON C.ID_CLIENTE = R.ID_CLIENTE AND C.ID_MASCOTA = R.ID_MASCOTA AND C.FECHA_CITA = R.FECHA_CITA
JOIN MASCOTAS M ON M.ID_MASCOTA = C.ID_MASCOTA AND M.ID_CLIENTE = C.ID_CLIENTE;

--Mascotas que han tenido al menos una cita
SELECT DISTINCT M.NOMBRE
FROM MASCOTAS M JOIN CITAS C ON M.ID_CLIENTE = C.ID_CLIENTE AND M.ID_MASCOTA = C.ID_MASCOTA;

SELECT *
FROM MASCOTAS M
WHERE EXISTS(SELECT *
            FROM CITAS C
            WHERE M.ID_MASCOTA = C.ID_MASCOTA AND M.ID_CLIENTE = C.ID_CLIENTE);

--Clientes que han traído alguna mascota a consulta
SELECT DISTINCT C.NOMBRE, CL.DNI
FROM CLIENTES CL JOIN CITAS C ON CL.ID_CLIENTE = C.ID_CLIENTE;

SELECT *
FROM CLIENTES C
WHERE EXISTS(SELECT *
            FROM CITAS CI
            WHERE C.ID_CLIENTE = CI.ID_CLIENTE);

--Citas atendidas por el veterinario Dr.Morales
SELECT A.FECHA_CITA, M.NOMBRE MASCOTA
FROM ATENCIONES A JOIN PERSONAL P ON A.ID_PERSONAL = P.ID_PERSONAL
JOIN MASCOTAS M ON A.ID_CLIENTE = M.ID_CLIENTE AND A.ID_MASCOTA = M.ID_MASCOTA
WHERE LOWER(P.NOMBRE) = 'dr. morales';

--(HECHO POR LA PROFE)
SELECT C.FECHA_CITA, MOTIVO, OBSERVACIONES, P.NOMBRE ATENDIDO, ROL
FROM CITAS C JOIN ATENCIONES A ON C.ID_MASCOTA = A.ID_MASCOTA AND C.ID_CLIENTE = A.ID_CLIENTE AND C.FECHA_CITA = A.FECHA_CITA
JOIN PERSONAL P ON A.ID_PERSONAL = P.ID_PERSONAL
WHERE UPPER(P.NOMBRE) = 'DR. MORALES';

--Mascotas sin ninguna cita y sus dueños
SELECT M.NOMBRE MASCOTA, C.NOMBRE DUEÑO
FROM MASCOTAS M JOIN CLIENTES C ON M.ID_CLIENTE = C.ID_CLIENTE
LEFT JOIN CITAS CI ON M.ID_CLIENTE = CI.ID_CLIENTE AND M.ID_MASCOTA = CI.ID_MASCOTA
WHERE CI.FECHA_CITA IS NULL;

--Citas sin diagnóstico
SELECT CI.ID_CLIENTE, CI.ID_MASCOTA, CI.FECHA_CITA, CI.MOTIVO
FROM CITAS CI LEFT JOIN DIAGNOSTICOS D ON CI.ID_CLIENTE = D.ID_CLIENTE AND CI.ID_MASCOTA = D.ID_MASCOTA
AND CI.FECHA_CITA = D.FECHA_CITA
WHERE D.ID_CLIENTE IS NULL;

--(HECHO POR LA PROFE), IMPORTANTE POR QUE PUEDE ENTRAR EN EL EXAMEN COMO UNICA OPCION EL HECHO DE REALIZARLA SOLO CON SUBCONSULTAS
SELECT C.FECHA_CITA, MOTIVO
FROM CITAS C
WHERE NOT EXISTS(SELECT *
                FROM DIAGNOSTICOS D
                WHERE C.ID_MASCOTA = D.ID_MASCOTA AND C.ID_CLIENTE = D.ID_CLIENTE AND C.FECHA_CITA = D.FECHA_CITA);

--Citas sin pago registrado
SELECT M.NOMBRE MASCOTA, CI.FECHA_CITA
FROM CITAS CI JOIN MASCOTAS M ON CI.ID_CLIENTE = M.ID_CLIENTE AND CI.ID_MASCOTA = M.ID_MASCOTA
LEFT JOIN PAGOS P ON CI.ID_CLIENTE = P.ID_CLIENTE AND C.ID_MASCOTA = P.ID_MASCOTA AND CI.FECHA_CITA = P.FECHA_CITA
WHERE P.ID_CLIENTE IS NULL;

SELECT *
FROM CITAS C
WHERE NOT EXISTS(SELECT 1 --El uno sirve de relleno ya que no hace falta poner nada en el select
                FROM PAGOS P
                WHERE P.ID_CLIENTE = C.ID_CLIENTE AND P.ID_MASCOTA = C.ID_MASCOTA AND P.FECHA_CITA = C.FECHA_CITA);

--Citas realizadas en el mismo mes que el mes de nacimiento de la mascota atendida
SELECT CI.FECHA_CITA, M.NOMBRE MASCOTA, M.FECHA_NAC
FROM CITAS CI JOIN MASCOTAS M ON CI.ID_CLIENTE = M.ID_CLIENTE AND CI.ID_MASCOTA = M.ID_MASCOTA
WHERE EXTRACT(MONTH FROM CI.FECHA_CITA) = EXTRACT(MONTH FROM M.FECHA_NAC);

--REQUIERE DEL USO DE UNA FUNCION EXTRACT(valor FROM fecha)

--Citas posteriores al 18 de febrero de 2024
SELECT *
FROM CITAS
WHERE FECHA_CITA > DATE '2024-01-18';

SELECT FECHA_CITA, CLI.NOMBRE DUEÑO, M.NOMBRE, MOTIVO
FROM CITAS C JOIN MASCOTAS M ON C.ID_CLIENTE = M.ID_CLIENTE AND C.ID_MASCOTA = M.ID_MASCOTA
JOIN CLIENTES CLI ON C.ID_CLIENTE = CLI.ID_CLIENTE
WHERE FECHA_CITA > DATE '2024-02-18';

--Mascotas nacidas antes del año 2020
SELECT NOMBRE, FECHA_NAC
FROM MASCOTAS
WHERE FECHA_NAC < DATE '2020-01-01';