CREATE TABLE CLIENTES ( 
    CLIENTE_NO NUMBER(3) CONSTRAINT CLIENTES_NUMERO_PK 
PRIMARY KEY, 
    NOMBRE VARCHAR2(30) 
); 

INSERT INTO CLIENTES VALUES (102, 'MARTA MARTÍNEZ MARTOS'); 
INSERT INTO CLIENTES VALUES (001, 'ANA ALONSO ÁLVAREZ'); 
INSERT INTO CLIENTES VALUES (600, 'MARCOS MÁRQUEZ MARÍN'); 
INSERT INTO CLIENTES VALUES (303, 'ALONSO ALONSO ALONSO'); 
INSERT INTO CLIENTES VALUES (99, 'MARTÍN RODRIGO RUIZ'); 
INSERT INTO CLIENTES VALUES (55, 'REMEDIOS RETUERTA RAMÍREZ');

DECLARE 
    -- v_nom tendrá exactamente el mismo tipo que la columna NOMBRE de CLIENTES
    v_nom CLIENTES.NOMBRE%TYPE; 
BEGIN 
    -- &vn_cli es una variable de sustitución; SQL Plus te pedirá el valor al ejecutar
    SELECT nombre INTO v_nom 
    FROM clientes 
    WHERE CLIENTE_NO=&vn_cli; 
    
    DBMS_OUTPUT.PUT_LINE(v_nom); 
END;