DROP TABLE AULA CASCADE CONSTRAINTS;
DROP TABLE RECURSO CASCADE CONSTRAINTS;
DROP TABLE USUARIO_CENTRO CASCADE CONSTRAINTS;
DROP TABLE RESERVA CASCADE CONSTRAINTS;
DROP TABLE RESERVA_RECURSO CASCADE CONSTRAINTS;

DROP ROLE ROLE_ADMIN_RESERVAS;
DROP ROLE ROLE_CONSULTA;
DROP ROLE ROLE_PROFESOR;

DROP USER PROF_JAVIER CASCADE;
DROP USER ADMIN_MARIA CASCADE;
DROP USER INVITADO CASCADE; 


CREATE TABLE AULAS (
    ID_AULA VARCHAR2 (10),
    NOMBRE VARCHAR2 (50),
    CAPACIDAD NUMBER (100),
    TIPO VARCHAR2 (20),
    CONSTRAINT AULA_ID_PK PRIMARY KEY (ID_AULA),
    CONSTRAINT TIPO_CH CHECK (TIPO IN ('Teórica','Informática','Taller','Laboratorio'))
);

CREATE TABLE RECURSOS (
    ID_RECURSO VARCHAR2 (9),
    NOMBRE VARCHAR2 (50),
    CATEGORIA VARCHAR2 (20),
    CONSTRAINT RECURSO_ID_PK PRIMARY KEY(ID_RECURSO),
    CONSTRAINT CATEGORIA_CH CHECK (CATEGORIA IN ('Proyecto','Portatil','Carro portátiles','Altavoces'))
);

CREATE USUARIOS_CENTRO (
    ID_USUARIO VARCHAR2 (9),
    NOMBRE VARCHAR2 (50),
    APELLIDO VARCHAR2 (50),
    TIPO VARCHAR2 (20),
    CONSTRAINT USUARIO_ID_PK PRIMARY KEY (ID_USUARIO),
    CONSTRAINT TIPO_CH CHECK (TIPO IN ('Profesor','Administración'))
);

CREATE TABLE RESERVAS(
    ID_RESERVA VARCHAR2 (9),
    ID_USUARIO VARCHAR2 (9),
    ID_AULA VARCHAR2 (10),
    FECHA_RESERVA DATE,
    HORA_INICIO NUMBER (2),
    HORA_FIN NUMBER (2),
    CONSTRAINT RESERVA_ID_PK PRIMARY KEY (ID_RESERVA),
    CONSTRAINT USUARIO_ID_FK FOREIGN KEY (ID_USUARIO) REFERENCES (USUARIO_CENTRO),
    CONSTRAINT AULA_ID_FK FOREIGN KEY (ID_AULA) REFERENCES (AULA),
);

CREATE TABLE RESERVAS_RECURSOS(
    ID_RESERVA VARCHAR2 (9),
    ID_RECURSO VARCHAR2 (9),
    CONSTRAINT ID_PK PRIMARY KEY (ID_RESERVA),
    CONSTRAINT RESERVA_ID_FK FOREIGN KEY (ID_RESERVA) REFERENCES (RESERVA),
    CONSTRAINT RECURSO_ID_FK FOREIGN KEY (ID_RECURSO) REFERENCES (RECURSO),
);

ALTER TABLE AULAS
    ADD DISPONIBLE VARCHAR2(2)
    DEFAULT 'Si'
    CHECK (DISPONIBLE IN ('Si','No'));

ALTER TABLE RECURSOS
    MODIFY NOMBRE VARCHAR2(80);

CREATE ROLE ROLE_ADMIN_RESERVAS;
CREATE ROLE ROLE_PROFESOR;
CREATE ROLE ROLE_CONSULTA;

GRANT CREATE SESSION TO ROLE_ADMIN_RESERVAS;
GRANT CREATE SESSION TO ROLE_PROFESOR;
GRANT CREATE SESSION TO ROLE_CONSULTA;    

GRANT SELECT, INSERT, UPDATE, DELETE ON AULAS TO ROLE_ADMIN_RESERVAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIOS_CENTRO TO ROLE_ADMIN_RESERVAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON RECURSOS TO ROLE_ADMIN_RESERVAS;
GRANT SELECT, DELETE ON RESERVAS TO ROLE_ADMIN_RESERVAS;

GRANT SELECT ON AULAS TO ROLE_PROFESOR;
GRANT SELECT ON RECURSOS TO ROLE_PROFESOR;
GRANT SELECT, INSERT, UPDATE ON RESERVAS TO ROLE_PROFESOR;
GRANT SELECT ON USUARIOS_CENTRO TO ROLE_PROFESOR;

GRANT SELECT ON AULAS TO ROLE_CONSULTA;
GRANT SELECT ON RECURSOS TO ROLE_CONSULTA;
GRANT SELECT ON USUARIOS_CENTRO TO ROLE_CONSULTA;
GRANT SELECT ON RESERVAS TO ROLE_CONSULTA;
GRANT SELECT ON RESERVAS_RECURSOS TO ROLE_CONSULTA;

CREATE USER PROF_JAVIER IDENTIFIED BY pass123;
CREATE USER ADMIN_MARIA IDENTIFIED BY pass123;
CREATE USER INVITADO IDENTIFIED BY invitado;

GRANT ROLE_ADMIN_RESERVAS TO ADMIN_MARIA;
GRANT ROLE_PROFESOR TO PROF_JAVIER;
GRANT ROLE_CONSULTA TO INVITADO;

REVOKE SELECT ON USUARIOS_CENTRO FROM ROLE_PROFESOR;