-- EJERCICIO 1
SELECT EMPLEADO_DNI, UNIVERSIDAD, ANIO
FROM ESTUDIOS
ORDER BY UNIVERSIDAD DESC, ANIO ASC;

-- EJERCICIO 2
SELECT *
FROM UNIVERSIDADES
WHERE CIUDAD IN ('SEVILLA', 'CÁDIZ');

-- EJERCICIO 3
SELECT NOMBRE_TRAB
FROM TRABAJOS
WHERE NOMBRE_TRAB NOT LIKE '%INGENIERO%';