--Funcion para validar la edad
CREATE OR REPLACE FUNCTION VALIDAEDAD (EDAD NUMBER)
RETURN VARCHAR2
AS
    CADENA VARCHAR2(40);
BEGIN
    IF EDAD >= 18 THEN
    CADENA := 'Mayor';
    ELSE
    CADENA := 'Menor'; END IF;

    RETURN CADENA;

END VALIDAEDAD;

--Funcion para validar el sexo
CREATE OR REPLACE FUNCTION VALIDASEXO (SEXO CHAR)
RETURN VARCHAR2
AS
    CADENA VARCHAR2(40);
BEGIN
    IF SEXO LIKE 'f' THEN
    CADENA := 'Femenino';
    ELSE
    CADENA := 'Masculino'; END IF;

    RETURN CADENA;

END VALIDASEXO;


-- Consulta
SELECT NOMBRE, VALIDAEDAD(EDAD) AS EDAD, VALIDASEXO(SEXO) AS SEXO
FROM PACIENTES;