--Funcion para validar la edad
CREATE OR REPLACE FUNCTION VALIDAEDAD (EDAD NUMBER)
RETURN VARCHAR2
AS
    CADENA VARCHAR2(40);
BEGIN
    IF EDAD >= 18 THEN
        CADENA := 'Mayor';
    ELSE
        CADENA := 'Menor'; 
    END IF;

    RETURN CADENA;

END VALIDAEDAD;

--Funcion para validar el sexo
CREATE OR REPLACE FUNCTION VALIDASEXO (SEXO CHAR)
RETURN VARCHAR2
AS
    CADENA VARCHAR2(40);
BEGIN
    IF LOWER(SEXO) = 'f' THEN
        CADENA := 'Femenino';
    ELSIF LOWER(SEXO) = 'm' THEN
        CADENA := 'Masculino'; 
    ELSE 
        CADENA := 'Otro';
    END IF;

    RETURN CADENA;

END VALIDASEXO;


-- Consulta
SELECT NOMBRE, VALIDAEDAD(EDAD) AS CATEGORIA, VALIDASEXO(SEXO) AS SEXO
FROM PACIENTES;