/*CREATE USER FuncionesSql IDENTIFIED BY FuncionesSql;
GRANT CREATE SESSION TO FuncionesSql;
GRANT CREATE TABLE TO FuncionesSql;
GRANT CREATE SEQUENCE TO FuncionesSql;
ALTER USER FuncionesSql QUOTA UNLIMITED ON USERS;*/

DROP TABLE USUARIOS CASCADE CONSTRAINT;
DROP TABLE PEDIDOS CASCADE CONSTRAINT;

CREATE TABLE USUARIOS(
  id_usuario NUMBER(3) GENERATED ALWAYS AS IDENTITY,
  nombre VARCHAR2(25),
  email VARCHAR2(50),
  fecha_nac DATE NOT NULL,
  fecha_alta DATE DEFAULT SYSDATE,
  ciudad VARCHAR2(50),
  CONSTRAINT USUARIOS_ID_PK PRIMARY KEY(ID_USUARIO),
  CONSTRAINT USUARIOS_FECHAS_CH CHECK (FECHA_ALTA > FECHA_NAC)
);

CREATE TABLE PEDIDOS(
  id_pedido NUMBER(3) GENERATED ALWAYS AS IDENTITY,
  id_usuario NUMBER(3),
  fecha_pedido DATE DEFAULT SYSDATE,
  importe NUMBER(5,2),
  estado VARCHAR2(10),
  CONSTRAINT PEDIDOS_ID_PK PRIMARY KEY (ID_PEDIDO),
  CONSTRAINT PEDIDOS_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS,
  CONSTRAINT PEDIDOS_ESTADO_CH CHECK (ESTADO IN ('C', 'E','P'))
);
