--CREATE USER teoriaJoin IDENTIFIED BY teoriaJoin;
--GRANT CREATE SESSION TO teoriaJoin;
--GRANT CREATE TABLE TO teoriaJoin;
--ALTER USER teoriaJoin QUOTA UNLIMITED ON USERS;

DROP TABLE ALUMNOS CASCADE CONSTRAINT;
DROP TABLE CURSOS CASCADE CONSTRAINT;
DROP TABLE PROFESORES CASCADE CONSTRAINT;
DROP TABLE MATRICULAS CASCADE CONSTRAINT;

CREATE TABLE alumnos (
    dni         VARCHAR2(9),
    nombre      VARCHAR2(30) NOT NULL,
    apellido1   VARCHAR2(30) NOT NULL,
    apellido2   VARCHAR2(30),
    provincia   VARCHAR2(30),
    CONSTRAINT ALUMNOS_DNI_PK PRIMARY KEY (DNI)
);

CREATE TABLE profesores (
    dni        VARCHAR2(9),
    nombre     VARCHAR2(30) NOT NULL,
    apellido1  VARCHAR2(30) NOT NULL,
    CONSTRAINT PROFESORES_DNI_PK PRIMARY KEY(DNI)
);

CREATE TABLE cursos (
    id_curso     NUMBER,
    nombre       VARCHAR2(50) NOT NULL,
    fecha_inicio DATE DEFAULT SYSDATE NOT NULL,
    fecha_fin    DATE NOT NULL,
    dni_profesor VARCHAR2(9),
    CONSTRAINT CURSOS_ID_PK PRIMARY KEY (ID_CURSO),
    CONSTRAINT CURSOS_PROFE_FK FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES,
    CONSTRAINT CURSOS_FECHAS_CH CHECK (FECHA_FIN > FECHA_INICIO)
);

CREATE TABLE matriculas (
    dni       VARCHAR2(9),
    id_curso  NUMBER,
    CONSTRAINT matriculas_PK PRIMARY KEY (dni, id_curso),
    CONSTRAINT MATRICULAS_alumno_FK FOREIGN KEY (dni) REFERENCES alumnos(dni),
    CONSTRAINT MATRICULAS_curso_FK FOREIGN KEY (id_curso) REFERENCES cursos(id_curso)
);
