--Nota media global registrada en la base de datos
SELECT AVG(NOTA) AS MEDIA_GLOBAL
FROM CALIFICACIONES;

--Nota máxima y mínima registrada
SELECT MAX(NOTA) AS NOTA_MAXIMA, MIN(NOTA) AS NOTA_MÍNIMA
FROM CALIFICACIONES;

--Nota media por alumno en cada RA redondeado a 2 decimales
SELECT A.NOMBRE AS NOMBRE_ALUMNO, RA.CODIGO AS RESULTADOS_APRENDIZAJE, ROUND(AVG(C.NOTA),2) AS MEDIA
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE
JOIN RESULTADOS_APRENDIZAJE RA ON CE.ID_RA = RA.ID_RA
GROUP BY A.NOMBRE, RA.CODIGO;

--Nota media por resultado de aprendizaje redondeada a dos decimales y ordenada por RA
SELECT RA.CODIGO AS RESULTADOS_APRENDIZAJE, ROUND(AVG(C.NOTA),2) AS MEDIA
FROM RESULTADOS_APRENDIZAJE RA JOIN CRITERIOS_EVALUACION CE ON RA.ID_RA = CE.ID_RA
JOIN CALIFICACIONES C ON C.ID_CE = CE.ID_CE
GROUP BY RA.CODIGO
ORDER BY RA.CODIGO;

--RAs cuya nota media es inferior a 5
SELECT RA.CODIGO AS RESULTADOS_APRENDIZAJE, ROUND(AVG(C.NOTA),2) AS MEDIA
FROM RESULTADOS_APRENDIZAJE RA JOIN CRITERIOS_EVALUACION CE ON RA.ID_RA = CE.ID_RA
JOIN CALIFICACIONES C ON C.ID_CE = CE.ID_CE
GROUP BY RA.CODIGO HAVING AVG(C.NOTA)<5;

--Alumnos con RAs no superados mostrando la nota en ese RA redondeada a 2 decimales y 
--la información del alumno debe incluir si es repetidor (Repetidor) o no (-) y su nombre y apellidos de la siguiente manera
--ALUMNO_A nombre apellidos
SELECT DECODE(A.REPETIDOR, 'S','Repetidor','N','-') || ' ' || A.NOMBRE || ' ' || A.APELLIDOS AS ALUMNO_A, RA.CODIGO AS RESULTADOS_APRENDIZAJE, ROUND(AVG(C.NOTA),2) AS MEDIA
FROM RESULTADOS_APRENDIZAJE RA JOIN CRITERIOS_EVALUACION CE ON RA.ID_RA = CE.ID_RA
JOIN CALIFICACIONES C ON C.ID_CE = CE.ID_CE
JOIN ALUMNOS A ON A.ID_ALUMNO = C.ID_ALUMNO
GROUP BY A.NOMBRE, A.APELLIDOS, A.REPETIDOR, RA.CODIGO HAVING AVG(C.NOTA)<5;

--Pruebas y número de criterios de evaluación evaluados en cada una de ellas
SELECT P.NOMBRE AS PRUEBA, COUNT(PC.ID_CE) AS NUM_CRITERIOS
FROM PRUEBAS_EVALUACION P JOIN PRUEBAS_CRITERIOS PC ON P.ID_PRUEBA = PC.ID_PRUEBA
GROUP BY P.NOMBRE;

--Alumnos con nota media superior a la media global
CREATE VIEW MEDIA_GLOBAL
AS
SELECT AVG(NOTA) AS MEDIA
FROM CALIFICACIONES;

SELECT A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOS AS APELLIDOS_ALUMNO
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
CROSS JOIN MEDIA_GLOBAL
GROUP BY A.NOMBRE, A.APELLIDOS, MEDIA_GLOBAL.MEDIA HAVING AVG(NOTA) > MEDIA_GLOBAL.MEDIA;

--Mejor nota de cada alumno en cada RA
SELECT A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOS AS APELLIDOS_ALUMNO, RA.ID_RA, MAX(C.NOTA)
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE
JOIN RESULTADOS_APRENDIZAJE RA ON RA.ID_RA = CE.ID_RA
GROUP BY A.NOMBRE, A.APELLIDOS, RA.ID_RA;

--UTILIZANDO OPERADORES DE CONJUNTOS
--Alumnos con notas en RA1 o RA6
SELECT A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOS AS APELLIDOS_ALUMNO, RA.ID_RA, C.NOTA
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE
JOIN RESULTADOS_APRENDIZAJE RA ON RA.ID_RA = CE.ID_RA
WHERE RA.ID_RA = 1
UNION
SELECT A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOS AS APELLIDOS_ALUMNO, RA.ID_RA, C.NOTA
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE
JOIN RESULTADOS_APRENDIZAJE RA ON RA.ID_RA = CE.ID_RA
WHERE RA.ID_RA = 6;

--Alumnos con notas en RA1 y RA6
SELECT A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOS AS APELLIDOS_ALUMNO
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE
JOIN RESULTADOS_APRENDIZAJE RA ON RA.ID_RA = CE.ID_RA
WHERE RA.ID_RA = 1
INTERSECT
SELECT A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOS AS APELLIDOS_ALUMNO
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE
JOIN RESULTADOS_APRENDIZAJE RA ON RA.ID_RA = CE.ID_RA
WHERE RA.ID_RA = 6;


--Alumnos con notas en RA1 pero no en RA6
SELECT A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOS AS APELLIDOS_ALUMNO
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE
JOIN RESULTADOS_APRENDIZAJE RA ON RA.ID_RA = CE.ID_RA
WHERE RA.ID_RA = 1
MINUS
SELECT A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOS AS APELLIDOS_ALUMNO
FROM ALUMNOS A JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CE ON C.ID_CE = CE.ID_CE
JOIN RESULTADOS_APRENDIZAJE RA ON RA.ID_RA = CE.ID_RA
WHERE RA.ID_RA = 6;

--Nota media por alumno y RA solo si supera el RA. Mostrar la información ordenada por nombre de alumno,
--apellidos y código de RA.
SELECT DECODE(A.REPETIDOR, 'S','Repetidor','N','-') || ' ' || A.NOMBRE || ' ' || A.APELLIDOS AS ALUMNO_A, RA.CODIGO AS RESULTADOS_APRENDIZAJE, ROUND(AVG(C.NOTA),2) AS MEDIA
FROM RESULTADOS_APRENDIZAJE RA JOIN CRITERIOS_EVALUACION CE ON RA.ID_RA = CE.ID_RA
JOIN CALIFICACIONES C ON C.ID_CE = CE.ID_CE
JOIN ALUMNOS A ON A.ID_ALUMNO = C.ID_ALUMNO
GROUP BY A.NOMBRE, A.APELLIDOS, A.REPETIDOR, RA.CODIGO HAVING AVG(C.NOTA)>5
ORDER BY A.NOMBRE,A.APELLIDOS,RA.CODIGO;

--¿Cuántos alumnos tienen que recuperar cada RA? Complicada
CREATE VIEW ALUMNOS_SUSPENSOS_RA 
AS
SELECT RA.CODIGO, A.ID_ALUMNO, ROUND(AVG(C.NOTA), 2) AS MEDIA
FROM RESULTADOS_APRENDIZAJE RA JOIN CRITERIOS_EVALUACION CE ON RA.ID_RA = CE.ID_RA
JOIN CALIFICACIONES C ON C.ID_CE = CE.ID_CE
JOIN ALUMNOS A ON A.ID_ALUMNO = C.ID_ALUMNO
GROUP BY A.ID_ALUMNO, RA.CODIGO HAVING AVG(C.NOTA) < 5;

SELECT CODIGO AS RESULTADO_APRENDIZAJE, COUNT(*) AS ALUMNOS_A_RECUPERAR
FROM ALUMNOS_SUSPENSOS_RA
GROUP BY CODIGO;

--¿Hay alumnos que no hayan hecho alguna prueba de evaluación? Complicada
SELECT A.NOMBRE, A.APELLIDOS, P.NOMBRE AS PRUEBA
FROM ALUMNOS A CROSS JOIN PRUEBAS_EVALUACION P
LEFT JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO AND C.ID_PRUEBA = P.ID_PRUEBA
WHERE C.ID_ALUMNO IS NULL;