/*
CREATE USER PrAlumnosRAsCEs IDENTIFIED BY PrAlumnosRAsCEs;
GRANT CREATE SESSION TO PrAlumnosRAsCEs;
GRANT CREATE TABLE TO PrAlumnosRAsCEs;
GRANT CREATE SEQUENCE TO PrAlumnosRAsCEs;
ALTER USER PrAlumnosRAsCEs QUOTA UNLIMITED ON USERS;
*/


-- =========================
-- TABLA DE ALUMNOS
-- =========================
CREATE TABLE alumnos (
    id_alumno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni              VARCHAR2(9) UNIQUE NOT NULL,
    nombre           VARCHAR2(50) NOT NULL,
    apellidos        VARCHAR2(80) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    repetidor        CHAR(1) CHECK (repetidor IN ('S','N'))
);

-- =========================
-- RESULTADOS DE APRENDIZAJE
-- =========================
CREATE TABLE resultados_aprendizaje (
    id_ra   NUMBER PRIMARY KEY,
    codigo  VARCHAR2(4) UNIQUE NOT NULL,
    descripcion VARCHAR2(200)
);

-- =========================
-- CRITERIOS DE EVALUACIÓN
-- =========================
CREATE TABLE criterios_evaluacion (
    id_ce   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ra   NUMBER NOT NULL,
    codigo  VARCHAR2(5) NOT NULL,
    descripcion VARCHAR2(200),
    CONSTRAINT fk_ce_ra FOREIGN KEY (id_ra) REFERENCES resultados_aprendizaje(id_ra),
    CONSTRAINT uk_ra_ce UNIQUE (id_ra, codigo)
);

-- =========================
-- PRUEBAS DE EVALUACIÓN
-- =========================
CREATE TABLE pruebas_evaluacion (
    id_prueba NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR2(100) NOT NULL,
    tipo      VARCHAR2(30), -- Examen, Práctica, Proyecto, Cuestionario...
    fecha     DATE NOT NULL,
    descripcion VARCHAR2(200)
);

-- Relación N:M entre pruebas y criterios
CREATE TABLE pruebas_criterios (
    id_prueba NUMBER,
    id_ce     NUMBER,
    CONSTRAINT pk_pruebas_criterios PRIMARY KEY (id_prueba, id_ce),
    CONSTRAINT fk_pc_prueba FOREIGN KEY (id_prueba) REFERENCES pruebas_evaluacion(id_prueba),
    CONSTRAINT fk_pc_ce FOREIGN KEY (id_ce) REFERENCES criterios_evaluacion(id_ce)
);

-- =========================
-- CALIFICACIONES
-- =========================
CREATE TABLE calificaciones (
    id_calificacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_alumno       NUMBER NOT NULL,
    id_prueba       NUMBER NOT NULL,
    id_ce           NUMBER NOT NULL,
    nota            NUMBER(4,2) CHECK (nota BETWEEN 0 AND 10),
    CONSTRAINT fk_cal_alumno FOREIGN KEY (id_alumno) REFERENCES alumnos(id_alumno),
    CONSTRAINT fk_cal_prueba FOREIGN KEY (id_prueba) REFERENCES pruebas_evaluacion(id_prueba),
    CONSTRAINT fk_cal_ce FOREIGN KEY (id_ce) REFERENCES criterios_evaluacion(id_ce),
    CONSTRAINT uk_cal UNIQUE (id_alumno, id_prueba, id_ce)
);
