/*CREATE USER ClinicaVeterinaria IDENTIFIED BY ClinicaVeterinaria;
GRANT CREATE SESSION TO ClinicaVeterinaria;
GRANT CREATE TABLE TO ClinicaVeterinaria;
ALTER USER ClinicaVeterinaria QUOTA UNLIMITED ON USERS;*/


DROP TABLE CLIENTES CASCADE CONSTRAINT;
DROP TABLE MASCOTAS CASCADE CONSTRAINT;
DROP TABLE PERSONAL CASCADE CONSTRAINT;
DROP TABLE CITAS CASCADE CONSTRAINT;
DROP TABLE ATENCIONES CASCADE CONSTRAINT;
DROP TABLE DIAGNOSTICOS CASCADE CONSTRAINT;
DROP TABLE RECOMENDACIONES CASCADE CONSTRAINT;
DROP TABLE PAGOS CASCADE CONSTRAINT;

CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER,
    DNI        VARCHAR2(9) NOT NULL,
    NOMBRE     VARCHAR2(50) NOT NULL,
    TELEFONO   VARCHAR2(15) NOT NULL,
    EMAIL      VARCHAR2(100) UNIQUE,
    CONSTRAINT CLIENTES_ID_PK PRIMARY KEY (ID_CLIENTE)
);
CREATE TABLE MASCOTAS (
    ID_CLIENTE NUMBER,
    ID_MASCOTA NUMBER,
    NOMBRE     VARCHAR2(50) NOT NULL,
    ESPECIE    VARCHAR2(30) NOT NULL,
    FECHA_NAC  DATE NOT NULL,
    CONSTRAINT MASCOTAS_ID_PK PRIMARY KEY (ID_CLIENTE, ID_MASCOTA),
    CONSTRAINT MASCOTAS_CLIENTES_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE PERSONAL (
    ID_PERSONAL NUMBER,
    NOMBRE      VARCHAR2(50) NOT NULL,
    ROL         VARCHAR2(30), -- Veterinario, Auxiliar...
    CONSTRAINT PERSONAL_ID_PK PRIMARY KEY (ID_PERSONAL),
    CONSTRAINT PERSONA_ROL_CH CHECK (ROL IN ('Veterinario', 'Auxiliar'))
);

CREATE TABLE CITAS (
    ID_CLIENTE NUMBER,
    ID_MASCOTA NUMBER,
    FECHA_CITA DATE NOT NULL,
    MOTIVO     VARCHAR2(200),
    CONSTRAINT CITAS_ID_PK PRIMARY KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA),
    CONSTRAINT CITAS_MASCOTAS_FK FOREIGN KEY (ID_CLIENTE, ID_MASCOTA) REFERENCES MASCOTAS(ID_CLIENTE, ID_MASCOTA)
);


CREATE TABLE ATENCIONES (
    ID_CLIENTE  NUMBER,
    ID_MASCOTA  NUMBER,
    FECHA_CITA  DATE NOT NULL,
    ID_PERSONAL NUMBER,
    OBSERVACIONES VARCHAR2(300),
    CONSTRAINT ATENCIONES_ID_PK PRIMARY KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA, ID_PERSONAL),
    CONSTRAINT ATENCIONES_CITAS_FK FOREIGN KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA) REFERENCES CITAS(ID_CLIENTE, ID_MASCOTA, FECHA_CITA),
    CONSTRAINT ATENCIONES_PERSONAL_FK FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL)
);


CREATE TABLE DIAGNOSTICOS (
    ID_CLIENTE NUMBER,
    ID_MASCOTA NUMBER,
    FECHA_CITA DATE,
    DESCRIPCION VARCHAR2(300),
    CONSTRAINT DIAGNOSTICOS_ID_PK PRIMARY KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA),
    CONSTRAINT DIAGNOSTICOS_CITAS_FK FOREIGN KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA) REFERENCES CITAS(ID_CLIENTE, ID_MASCOTA, FECHA_CITA)
);

CREATE TABLE RECOMENDACIONES (
    ID_CLIENTE NUMBER,
    ID_MASCOTA NUMBER,
    FECHA_CITA DATE,
    TEXTO      VARCHAR2(300),
    CONSTRAINT RECOMENDACIONES_ID_PK PRIMARY KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA),
    CONSTRAINT RECOMENDACIONES_CITAS_FK FOREIGN KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA) REFERENCES CITAS(ID_CLIENTE, ID_MASCOTA, FECHA_CITA)
);

CREATE TABLE PAGOS (
    ID_CLIENTE NUMBER,
    ID_MASCOTA NUMBER,
    FECHA_CITA DATE,
    IMPORTE    NUMBER(8,2),
    FECHA_PAGO DATE,
    CONSTRAINT PAGOS_OD_PK PRIMARY KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA),
    CONSTRAINT PAGOS_CITAS_FK FOREIGN KEY (ID_CLIENTE, ID_MASCOTA, FECHA_CITA) REFERENCES CITAS(ID_CLIENTE, ID_MASCOTA, FECHA_CITA)
);
