--1
SELECT * 
FROM EMP;  

SELECT * 
FROM DEPT;

--2
SELECT EMP_NO, APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO = 20
ORDER BY APELLIDO;

SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO = 'ANALISTA'
ORDER BY EMP_NO;

SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLE
WHERE DEPT_NO = 10 AND OFICIO = 'ANALISTA'
ORDER BY APELLIDO DESC, EMP_NO DESC;

--3
SELECT *
FROM ALUM0405;

SELECT DNI,  NOMBRE,  APELLIDOS,  CURSO, NIVEL, CLASE
FROM ALUM0405;

SELECT *
FROM ALUM0405
WHERE POBLACION = 'GUADALAJARA';

SELECT NOMBRE, APELLIDOS
FROM ALUM0405
WHERE POBLACION = 'GUADALAJARA';

SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE
FROM ALUM0405
ORDER BY APELLIDOS, NOMBRE;

--4
SELECT DEPT_NO AS "Número Departamento", DNOMBRE AS "Departamento"
FROM DEPARTS;

--5
SELECT NOMBRE_ALUMNO, (NOTA+NOTA2+NOTA3)/3 AS MEDIA
FROM NOTAS_ALUMNOS;

--6
SELECT NOMBRE_ALUMNO, NOTA1, (NOTA+NOTA2+NOTA3)/3 AS MEDIA
FROM NOTAS_ALUMNOS
WHERE NOTA1 = 7 AND (NOTA+NOTA2+NOTA3)/3 > 6;

--7
SELECT APELLIDO
FROM EMPLE
WHERE APELLIDO LIKE 'J%'

SELECT APELLIDO
FROM EMPLE
WHERE APELLIDO LIKE '_R%'

SELECT APELLIDO
FROM EMPLE
WHERE APELLIDO LIKE 'A%O%'

--8
SELECT * 
FROM LIBRERIA 
WHERE TEMA = 'LABORES';


SELECT * 
FROM LIBRERIA 
WHERE TEMA LIKE 'LABORES';

--Esta es la mejor
SELECT * 
FROM LIBRERIA 
WHERE TEMA LIKE 'LABORES%';

--9
SELECT APELLIDO 
FROM EMPLE 
WHERE DEPT_NO IN (10, 30);

SELECT APELLIDO 
FROM EMPLE 
WHERE DEPT_NO NOT IN (10, 30);

SELECT APELLIDO 
FROM EMPLE 
WHERE OFICIO IN ('VENDEDOR', 'ANALISTA', 'EMPLEADO');

SELECT APELLIDO 
FROM EMPLE 
WHERE OFICIO NOT IN ('VENDEDOR', 'ANALISTA', 'EMPLEADO');

--10
SELECT APELLIDO, SALARIO 
FROM EMPLE 
WHERE SALARIO BETWEEN 1500 AND 2000;
SELECT APELLIDO, SALARIO 
FROM EMPLE 
WHERE SALARIO NOT BETWEEN 1500 AND 2000;

--11
SELECT APELLIDO, SALARIO, DEPT_NO
FROM EMPLE
WHERE SALARIO > 2000 AND (DEPT_NO = 10 OR DEPT_NO = 20);

SELECT APELLIDO, SALARIO, DEPT_NO
FROM EMPLE
WHERE SALARIO > 2000 AND DEPT_NO IN (10, 20);

--12
SELECT APELLIDO
FROM EMPLE
WHERE OFICIO = (SELECT OFICIO 
                FROM EMPLE 
                WHERE APELLIDO = 'GIL');

--13
SELECT APELLIDO, OFICIO, SALARIO, FECHA_ALT
FROM EMPLE
WHERE OFICIO = (SELECT OFICIO 
                FROM EMPLE 
                WHERE APELLIDO = 'JIMENEZ') OR SALARIO >= (SELECT SALARIO 
                FROM EMPLE 
                WHERE APELLIDO = 'FERNANDEZ');

--14
SELECT E.APELLIDO, E.OFICIO, E.EMP_NO, D.DNOMBRE, D.LOC
FROM EMPLE E, DEPARTS D
WHERE E.DEPT_NO = D.DEPT_NO;

SELECT E.APELLIDO, E.OFICIO, E.EMP_NO, D.DNOMBRE, D.LOC
FROM EMPLE E, DEPARTS D
WHERE E.DEPT_NO = D.DEPT_NO AND D.LOC IN ('MADRID', 'BARCELONA');

SELECT E.APELLIDO, E.OFICIO
FROM EMPLE E, DEPARTS D
WHERE E.DEPT_NO = D.DEPT_NO AND E.DEPT_NO = 20 AND E.OFICIO IN (SELECT OFICIO 
                                                                FROM EMPLE WHERE DEPT_NO = (SELECT DEPT_NO 
                                                                                            FROM DEPARTS 
                                                                                            WHERE DNOMBRE = 'VENTAS')
);

SELECT APELLIDO
FROM EMPLE
WHERE (OFICIO, SALARIO) = (SELECT OFICIO, SALARIO 
                            FROM EMPLE 
                            WHERE APELLIDO = 'GIL');

SELECT APELLIDO
FROM EMPLE
WHERE OFICIO = (SELECT OFICIO 
                FROM EMPLE 
                WHERE APELLIDO = 'GIL') AND SALARIO = (SELECT SALARIO 
                                                        FROM EMPLE 
                                                        WHERE APELLIDO = 'GIL');

--15
SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO = (SELECT OFICIO 
                FROM EMPLE 
                WHERE APELLIDO = 'JIMENEZ') AND APELLIDO <> 'JIMENEZ';

-- Mismo dpto y salario que FERNANDEZ
SELECT APELLIDO, OFICIO, SALARIO
FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO 
                FROM EMPLE 
                WHERE APELLIDO = 'FERNANDEZ') AND SALARIO = (SELECT SALARIO 
                                                            FROM EMPLE 
                                                            WHERE APELLIDO = 'FERNANDEZ') AND APELLIDO <> 'FERNANDEZ';

--16
SELECT E.APELLIDO, E.OFICIO, E.EMP_NO, D.DNOMBRE, D.LOC
FROM EMPLE E, DEPARTS D;

SELECT E.APELLIDO, E.OFICIO, E.EMP_NO, D.DNOMBRE, D.LOC
FROM EMPLE E, DEPARTS D
WHERE E.DEPT_NO = D.DEPT_NO;

SELECT AL.APENOM, AS2.NOMBRE, N.NOTA
FROM ALUMNOS AL, ASIGNATURAS AS2, NOTAS N
WHERE AL.DNI = N.DNI AND AS2.COD = N.COD;

SELECT AL.APENOM
FROM ALUMNOS AL, ASIGNATURAS AS2, NOTAS N
WHERE AL.DNI = N.DNI AND AS2.COD = N.COD AND AS2.NOMBRE = 'FOL';

--17
SELECT AL.APENOM
FROM ALUMNOS AL, ASIGNATURAS AS2, NOTAS N
WHERE AL.DNI = N.DNI AND AS2.COD = N.COD AND AS2.NOMBRE = 'FOL' AND N.NOTA BETWEEN 7 AND 8;

SELECT AS2.NOMBRE
FROM ASIGNATURAS AS2
WHERE AS2.COD NOT IN (SELECT COD 
                    FROM NOTAS 
                    WHERE NOTA < 5);
