CREATE OR REPLACE PROCEDURE GENERAR_INFORME_PRACTICAS_EMPRESA(EMPRESA NUMBER)
AS

    CURSOR C_EMPRESAS IS SELECT * FROM EMPRESAS;
    CURSOR C_PRACTICAS_EMPRESAS(NUM_EMPRESA NUMBER) IS SELECT * FROM PRACTICAS WHERE EMPRESA_ID = NUM_EMPRESA;
    
    V_EMPRESA_ENTRADA NUMBER;
    V_EXISTE_EMPRESA_ENTRADA NUMBER;
    --DATOS INFORME
    V_NOMBRE_EMPRESA EMPRESAS.NOMBRE%TYPE;
    V_TOTAL_PRACTICAS NUMBER;
    V_PRACTICAS_FINALIZADAS NUMBER;
    V_PROMEDIO_EVAS NUMBER;
    V_CUENTA_EVAS NUMBER;

    EXCEPTION_EMPRESA_ENTRADA_NO_EXISTE EXCEPTION;

BEGIN
    --VERIFICAR SI ME PASAN EMPRESA COMO PARÁMETRO
    IF EMPRESA IS NULL THEN V_EMPRESA_ENTRADA := 0;
    ELSE V_EMPRESA_ENTRADA := 1;
    END IF;

    --VERIFICAR SI EXISTE LA EMPRESA PASADA COMO PARÁMETRO
    IF V_EMPRESA_ENTRADA = 1 THEN
        SELECT COUNT(*) INTO V_EXISTE_EMPRESA_ENTRADA FROM EMPRESAS WHERE EMPRESA_ID = EMPRESA;
    END IF;

    IF V_EXISTE_EMPRESA_ENTRADA = 0 THEN
        RAISE EXCEPTION_EMPRESA_ENTRADA_NO_EXISTE;
    END IF;

    --CASO ME PASAN LA EMPRESA COMO PARÁMETRO
    DBMS_OUTPUT.PUT_LINE('-----------------------INFORME PRÁCTICAS EMPRESA-----------------------');
    IF (V_EMPRESA_ENTRADA = 1) THEN
        --NOMBRE DE LA EMPRESA
        SELECT NOMBRE INTO V_NOMBRE_EMPRESA FROM EMPRESAS WHERE EMPRESA_ID = EMPRESA;
        --TOTAL DE PRÁCTICAS
        SELECT COUNT(EMPRESA_ID) INTO V_TOTAL_PRACTICAS FROM PRACTICAS WHERE EMPRESA_ID = EMPRESA;
        --TOTAL PRÁCTICAS FINALIZADAS
        SELECT COUNT(EMPRESA_ID) INTO V_PRACTICAS_FINALIZADAS
        FROM PRACTICAS
        WHERE EMPRESA_ID = EMPRESA AND ESTADO = 'Finalizada';
        --PROMEDIO DE EVALUACIONES
        SELECT AVG(EVALUACION), COUNT(*) INTO V_PROMEDIO_EVAS, V_CUENTA_EVAS
        FROM PRACTICAS
        WHERE EMPRESA_ID = EMPRESA AND EVALUACION IS NOT NULL;

        DBMS_OUTPUT.PUT_LINE('EMPRESA: '||EMPRESA ||' '||V_NOMBRE_EMPRESA);
        DBMS_OUTPUT.PUT_LINE('TOTAL DE PRÁCTICAS: '||V_TOTAL_PRACTICAS);
        DBMS_OUTPUT.PUT_LINE('PRÁCTICAS FINALIZADAS: '||V_PRACTICAS_FINALIZADAS);
        
        IF (V_CUENTA_EVAS != 0) THEN
            DBMS_OUTPUT.PUT_LINE('PROMEDIO DE EVALUACIONES: '|| V_PROMEDIO_EVAS);
        ELSE
            DBMS_OUTPUT.PUT_LINE('NO TIENE AÚN EVALUACIONES HECHAS');
        END IF;
        
        DBMS_OUTPUT.PUT_LINE('-----------------------------------------------------------------------');
        DBMS_OUTPUT.PUT_LINE('-----------------------------------------------------------------------');

    ELSE
        --NO ME PASAN EMPRESA COMO PARÁMETRO HAGO INFORME PARA CADA EMPRESA
        FOR V_C1 IN C_EMPRESAS LOOP
            --BUCLE POR CADA EMPRESA
            FOR V_C2 IN C_PRACTICAS_EMPRESAS(V_C1.EMPRESA_ID) LOOP
                --BUCLE POR PRÁCTICA POR EMPRESA
                --TOTAL DE PRÁCTICAS
                SELECT COUNT(EMPRESA_ID) INTO V_TOTAL_PRACTICAS FROM PRACTICAS WHERE EMPRESA_ID = V_C1.EMPRESA_ID;
                --TOTAL PRÁCTICAS FINALIZADAS
                SELECT COUNT(EMPRESA_ID) INTO V_PRACTICAS_FINALIZADAS
                FROM PRACTICAS
                WHERE EMPRESA_ID = V_C1.EMPRESA_ID AND ESTADO = 'Finalizada';
                --PROMEDIO DE EVALUACIONES
                SELECT AVG(EVALUACION), COUNT(*) INTO V_PROMEDIO_EVAS, V_CUENTA_EVAS
                FROM PRACTICAS
                WHERE EMPRESA_ID = V_C1.EMPRESA_ID AND EVALUACION IS NOT NULL;
            END LOOP;

            --SACO DATOS POR PANTALLA
            DBMS_OUTPUT.PUT_LINE('EMPRESA: ' || V_C1.EMPRESA_ID || ' ' || V_C1.NOMBRE);
            DBMS_OUTPUT.PUT_LINE('TOTAL DE PRÁCTICAS: '||V_TOTAL_PRACTICAS);
            DBMS_OUTPUT.PUT_LINE('PRÁCTICAS FINALIZADAS: '||V_PRACTICAS_FINALIZADAS);
            
            IF (V_CUENTA_EVAS != 0) THEN
                DBMS_OUTPUT.PUT_LINE('PROMEDIO DE EVALUACIONES: '|| V_PROMEDIO_EVAS);
            ELSE
                DBMS_OUTPUT.PUT_LINE('NO TIENE AÚN EVALUACIONES HECHAS');
            END IF;
        END LOOP;
    END IF;

EXCEPTION
    WHEN EXCEPTION_EMPRESA_ENTRADA_NO_EXISTE THEN
        DBMS_OUTPUT.PUT_LINE('LA EMPRESA RECIBIDA COMO PARÁMETRO NO ESTÁ REGISTRADA EN LA BASE DE DATOS');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('HA OCURRIDO UN ERROR INESPERADO: ' || SQLERRM);
END;