CREATE OR REPLACE PROCEDURE ACTUALIZAR_ESTADO_PRACTICAS
AS

CURSOR C_PRACTICAS IS SELECT PRACTICA_ID, FECHA_INICIO, FECHA_FIN, ESTADO
    FROM PRACTICAS
    WHERE ESTADO = 'Pendiente' OR ESTADO = 'En curso'
    FOR UPDATE;

V_ESTADO_NUEVO PRACTICAS.ESTADO%TYPE;
V_ESTADO_VIEJO PRACTICAS.ESTADO%TYPE;
V_PRACTICA PRACTICAS.PRACTICA_ID%TYPE;

BEGIN

    FOR V_CURSOR IN C_PRACTICAS LOOP

        V_ESTADO_VIEJO := V_CURSOR.ESTADO;

        IF V_CURSOR.ESTADO = 'En curso' AND V_CURSOR.FECHA_FIN <= SYSDATE THEN
            V_ESTADO_NUEVO := 'Finalizada';
        ELSIF V_CURSOR.ESTADO = 'Pendiente' AND V_CURSOR.FECHA_INICIO <= SYSDATE +5 THEN
            V_ESTADO_NUEVO := 'En curso';
        ELSE
            V_ESTADO_NUEVO := V_CURSOR.ESTADO;
        END IF;

        IF V_ESTADO_NUEVO != V_ESTADO_VIEJO THEN
            UPDATE PRACTICAS SET ESTADO = V_ESTADO_NUEVO
            WHERE CURRENT OF C_PRACTICAS;
        END IF;

        DBMS_OUTPUT.PUT_LINE('Actualizada la práctica ' || V_PRACTICA || ', de ' || V_ESTADO_VIEJO || ' a ' || V_ESTADO_NUEVO);

    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Se han deshecho las operaciones debido a un error inesperado.');
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END;