CREATE USER practicaIndividualTema6 IDENTIFIED BY practicaIndividualTema6;

GRANT CREATE SESSION TO practicaIndividualTema6 WITH ADMIN OPTION;
GRANT CREATE TABLE TO practicaIndividualTema6 WITH ADMIN OPTION;

--PROCEDURE
GRANT CREATE PROCEDURE TO practicaIndividualTema6;

--TRIGGER
GRANT CREATE TRIGGER TO practicaIndividualTema6;

GRANT CREATE SEQUENCE TO practicaIndividualTema6;

ALTER USER practicaIndividualTema6 QUOTA UNLIMITED ON USERS;