CREATE USER practicaFP IDENTIFIED BY practicaFP;

GRANT CREATE SESSION TO practicaFP WITH ADMIN OPTION;
GRANT CREATE TABLE TO practicaFP WITH ADMIN OPTION;

--PROCEDURE
GRANT CREATE PROCEDURE TO practicaFP;

--TRIGGER
GRANT CREATE TRIGGER TO practicaFP;

GRANT CREATE SEQUENCE TO practicaFP;

ALTER USER practicaFP QUOTA UNLIMITED ON USERS;