-- EJERCICIO 4.1
SELECT E.NOMBRE, E.APELLIDO1, HS.SALARIO, HS.FECHA_COMIENZO
FROM EMPLEADOS E, HISTORIAL_SALARIAL HS
WHERE E.DNI = HS.EMPLEADO_DNI
ORDER BY E.NOMBRE, HS.FECHA_COMIENZO;

-- EJERCICIO 4.2
SELECT T.NOMBRE_TRAB, T.SALARIO_MIN, T.SALARIO_MAX, HL.FECHA_INICIO, HL.FECHA_FIN
FROM HISTORIAL_LABORAL HL, TRABAJOS T
WHERE HL.TRAB_COD = T.TRABAJO_COD AND HL.EMPLEADO_DNI = 12345;