--1--

--USUARIOS
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, EMAIL, SALDO)
VALUES(1, 'Ana López', 'ana@mail.com', 15);

INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, EMAIL, SALDO)
VALUES(2, 'Carlos Ruiz', 'carlos@mail.com', 8);

INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, EMAIL, SALDO)
VALUES(3, 'Lucía Pérez', 'lucia@mail.com', 12);

INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, EMAIL, SALDO)
VALUES(4, 'Mario Díaz', 'mario@mail.com', 5);

--ESTACIONES
INSERT INTO ESTACIONES (ID_ESTACION, NOMBRE, UBICACION)
VALUES(1, 'Biblioteca', 'Campus Norte');

INSERT INTO ESTACIONES (ID_ESTACION, NOMBRE, UBICACION)
VALUES(2, 'Residencia', 'Campus Sur');

INSERT INTO ESTACIONES (ID_ESTACION, NOMBRE, UBICACION, CAPACIDAD)
VALUES(3, 'Centro Comercial', 'Zona Centro', 12);

--PATINETES
INSERT INTO PATINETES (ID_PATINETE, MODELO, ESTADO, ID_ESTACION)
VALUES(101, 'Xiamo Pro 1', 'DISPONIBLE', 1);

INSERT INTO PATINETES (ID_PATINETE, MODELO, ESTADO, ID_ESTACION)
VALUES(103, 'Segway Ninebot 1', 'DISPONIBLE', 2);

INSERT INTO PATINETES (ID_PATINETE, MODELO, ESTADO, ID_ESTACION)
VALUES(104, 'Segway Ninebot 2', 'DISPONIBLE', 2);

INSERT INTO PATINETES (ID_PATINETE, MODELO, ESTADO, ID_ESTACION)
VALUES(102, 'Xiamo Pro 2', 'DISPONIBLE', 1);

INSERT INTO PATINETES (ID_PATINETE, MODELO, ESTADO, ID_ESTACION)
VALUES(105, 'Xiamo Lite', 'DISPONIBLE', 3);

--ALQUILERES
INSERT INTO ALQUILERES(ID_ALQUILER, ID_USUARIO, ID_PATINETE, FECHA_INICIO, FECHA_FIN, COSTE)
VALUES(1, 1, 101, DATE '2025-10-10', DATE '2025-10-11', 3);

INSERT INTO ALQUILERES(ID_ALQUILER, ID_USUARIO, ID_PATINETE, FECHA_INICIO, FECHA_FIN, COSTE)
VALUES(2, 2, 103, DATE '2025-10-11', DATE '2025-10-12', 2.5);

INSERT INTO ALQUILERES(ID_ALQUILER, ID_USUARIO, ID_PATINETE, FECHA_INICIO, FECHA_FIN, COSTE)
VALUES(3, 1, 104, DATE '2025-10-12', DATE '2025-10-13', 4);

COMMIT;

--2--
INSERT INTO HISTORIAL_ALQUILERES
SELECT ID_USUARIO, COUNT(ID_ALQUILER), SUM(COSTE)
        FROM ALQUILERES
        GROUP BY ID_USUARIO;

COMMIT;
--3--

--Guion 1
INSERT INTO ALQUILERES (ID_ALQUILER, ID_USUARIO, ID_PATINETE, FECHA_INICIO, COSTE)
VALUES((SELECT MAX(ID_ALQUILER)+1
        FROM ALQUILERES),
        (SELECT ID_USUARIO
        FROM USUARIOS 
        WHERE UPPER(NOMBRE) LIKE '%MARIO DÍAZ%'),
        (SELECT ID_PATINETE
        FROM PATINETES
        WHERE UPPER(MODELO) LIKE '%XIAOMI PRO 2%'),
        SYSDATE,
        3);

UPDATE USUARIOS
SET SALDO = SALDO - 3
WHERE UPPER(NOMBRE) LIKE '%MARIO DÍAZ%';

UPDATE PATINETES
SET ESTADO = 'ALQUILADO'
WHERE UPPER(MODELO) LIKE '%XIAOMI PRO 2%';

COMMIT;

--Guion 2
INSERT INTO ALQUILERES (ID_ALQUILER, ID_USUARIO, ID_PATINETE, FECHA_INICIO, COSTE)
VALUES((SELECT MAX(ID_ALQUILER)+1
        FROM ALQUILERES),
        (SELECT ID_USUARIO
        FROM USUARIOS 
        WHERE UPPER(NOMBRE) LIKE '%LUCÍA PÉREZ%'),
        (SELECT ID_PATINETE
        FROM PATINETES
        WHERE UPPER(MODELO) LIKE '%XIAOMI LITE%'),
        SYSDATE,
        4);


UPDATE USUARIOS
SET SALDO = SALDO - 4
WHERE UPPER(NOMBRE) LIKE '%LUCÍA PÉREZ%';

SAVEPOINT REGISTRO_ALQUILER;

UPDATE PATINETES
SET ESTADO = 'ALQUILADO'
WHERE UPPER(MODELO) LIKE '%XIAOMI LITE%';

ROLLBACK TO REGISTRO_ALQUILER;

COMMIT;

--Guion 3
INSERT INTO ALQUILERES (ID_ALQUILER, ID_USUARIO, ID_PATINETE, FECHA_INICIO, COSTE)
VALUES((SELECT MAX(ID_ALQUILER)+1
        FROM ALQUILERES),
        (SELECT ID_USUARIO
        FROM USUARIOS 
        WHERE UPPER(NOMBRE) LIKE '%CARLOS RUIZ%'),
        (SELECT ID_PATINETE
        FROM PATINETES
        WHERE UPPER(MODELO) LIKE '%XIAOMI PRO 1%'),
        SYSDATE,
        4);


UPDATE USUARIOS
SET SALDO = SALDO - 5
WHERE UPPER(NOMBRE) LIKE '%CARLOS RUIZ%';

UPDATE PATINETES
SET ESTADO = 'ALQUILADO'
WHERE UPPER(MODELO) LIKE '%XIAOMI PRO 1%';

ROLLBACK;
