/*DROP TABLE FAMILIAS CASCADE CONSTRAINTS;
DROP TABLE INSTRUMENTOS CASCADE CONSTRAINTS;
DROP TABLE MUSICOS CASCADE CONSTRAINTS;
DROP TABLE INSTRUMENTOS_HIST CASCADE CONSTRAINTS;*/

CREATE TABLE FAMILIAS
(
  ID_FAMILIA  VARCHAR2(4 BYTE)                  NOT NULL,
  NOMBRE      VARCHAR2(20 BYTE)                 NOT NULL
);


ALTER TABLE FAMILIAS ADD (
  CONSTRAINT PK_FAMILIA
  PRIMARY KEY
  (ID_FAMILIA));


CREATE TABLE INSTRUMENTOS
(
  CODIGO   VARCHAR2(3 BYTE),
  NOMBRE   VARCHAR2(20 BYTE)                    NOT NULL,
  PRECIO   NUMBER(4)                            NOT NULL,
  FAMILIA  VARCHAR2(4 BYTE)
);


ALTER TABLE INSTRUMENTOS ADD (
  CONSTRAINT INSTRUMENTOS_PK
  PRIMARY KEY
  (CODIGO),
  CONSTRAINT UNIQUE_NOMBRE_INSTR
  UNIQUE (NOMBRE));


CREATE TABLE MUSICOS
(
  ID            VARCHAR2(6 BYTE)                NOT NULL,
  NOMBRE        VARCHAR2(20 BYTE)               NOT NULL,
  NACIONALIDAD  VARCHAR2(20 BYTE)               NOT NULL,
  EXPERIENCIA   NUMBER                          NOT NULL,
  INSTRUMENTO   VARCHAR2(20 BYTE)               NOT NULL
);



ALTER TABLE MUSICOS ADD (
  CONSTRAINT MUSICOS_PK
  PRIMARY KEY
  (ID));


ALTER TABLE MUSICOS ADD (
  CONSTRAINT FK_INTRUMENTO 
  FOREIGN KEY (INSTRUMENTO) 
  REFERENCES INSTRUMENTOS (NOMBRE));



CREATE TABLE INSTRUMENTOS_HIST
(
  CODIGO   VARCHAR2(3 BYTE)                     NOT NULL,
  NOMBRE   VARCHAR2(15 BYTE)                    NOT NULL,
  PRECIO   NUMBER                               NOT NULL,
  FAMILIA  VARCHAR2(4 BYTE)                     NOT NULL
);


Insert into FAMILIAS
   (ID_FAMILIA, NOMBRE)
 Values
   ('0001', 'CUERDA');
Insert into FAMILIAS
   (ID_FAMILIA, NOMBRE)
 Values
   ('0002', 'VIENTO');
Insert into FAMILIAS
   (ID_FAMILIA, NOMBRE)
 Values
   ('0003', 'TECLADOS');
Insert into FAMILIAS
   (ID_FAMILIA, NOMBRE)
 Values
   ('0004', 'PERCUSIÓN');
Insert into INSTRUMENTOS
   (CODIGO, NOMBRE, PRECIO, FAMILIA)
 Values
   ('123', 'VIOLÍN', 1800, '0001');
Insert into INSTRUMENTOS
   (CODIGO, NOMBRE, PRECIO, FAMILIA)
 Values
   ('234', 'FLAUTA', 2500, '0002');
Insert into INSTRUMENTOS
   (CODIGO, NOMBRE, PRECIO, FAMILIA)
 Values
   ('233', 'ACORDEÓN', 3000, '0003');
Insert into INSTRUMENTOS
   (CODIGO, NOMBRE, PRECIO, FAMILIA)
 Values
   ('433', 'BODHRAM', 250, '0004');
Insert into INSTRUMENTOS
   (CODIGO, NOMBRE, PRECIO, FAMILIA)
 Values
   ('334', 'GAITA', 1200, '0002');
Insert into INSTRUMENTOS
   (CODIGO, NOMBRE, PRECIO, FAMILIA)
 Values
   ('444', 'BOUZOUKI', 1500, '0001');
Insert into INSTRUMENTOS
   (CODIGO, NOMBRE, PRECIO, FAMILIA)
 Values
   ('555', 'MANDOLINA', 800, '0001');
Insert into INSTRUMENTOS
   (CODIGO, NOMBRE, PRECIO, FAMILIA)
 Values
   ('666', 'BANJOI', 1000, '0001');

Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('111111', 'MICHEL GAVOTTE', 'FRANCIA', 2, 'FLAUTA');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('123456', 'JEAN FORET', 'BÉLGICA', 4, 'FLAUTA');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('234567', 'LUIS MECO', 'ESPAÑA', 1, 'ACORDEÓN');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('222333', 'MARÍA SMITH', 'REINO UNIDO', 12, 'ACORDEÓN');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('444555', 'ELOISE PRUNELLE', 'FRANCIA', 2, 'ACORDEÓN');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('111123', 'DANIELE PITINELI', 'ITALIA', 7, 'VIOLÍN');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('333445', 'EVARISTE CHALOP', 'SUIZA', 5, 'BODHRAM');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('445567', 'ARTHUR MCLEOD', 'IRLANDA', 3, 'VIOLÍN');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('221234', 'MARISA RUIZ', 'ESPAÑA', 2, 'ACORDEÓN');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('333333', 'ANXO PINTELA', 'ESPAÑA', 10, 'GAITA');
Insert into MUSICOS
   (ID, NOMBRE, NACIONALIDAD, EXPERIENCIA, INSTRUMENTO)
 Values
   ('555555', 'DENIS ROULAKIS', 'GRECIA', 4, 'BOUZOUKI');
