CREATE USER ejemploDDL IDENTIFIED BY ejemploDDL;

GRANT CREATE SESSION TO ejemploDDL WITH ADMIN OPTION;
GRANT CREATE TABLE TO ejemploDDL WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO ejemploDDL;
GRANT CREATE TRIGGER TO practicaGuiadaDisparadores;


/*ROLES*/
GRANT CREATE ROLE TO ejemploDDL;
GRANT DROP ANY ROLE TO ejemploDDL;
/*USUARIOS*/
GRANT CREATE USER TO ejemploDDL;
GRANT DROP USER TO ejemploDDL;

GRANT CREATE SEQUENCE TO ejemploDDL;

ALTER USER ejemploDDL QUOTA UNLIMITED ON USERS;