--1.Número total de clientes.
SELECT ID_CLIENTE, COUNT(*) AS NUMERO_CLIENTES
FROM CLIENTES;

--2.Número total de mascotas.
SELECT ID_MASCOTA, COUNT(*) AS NUMERO_MASCOTAS
FROM MASCOTAS;

--3.Número total de citas.
SELECT FECHA_CITA, COUNT(*) AS NUMERO_CITAS
FROM CITAS;

--4.Número de pagos realizados.
SELECT FECHA_PAGO, COUNT(*) AS NUMERO_PAGOS
FROM PAGOS;

--5.Número de citas sin pago.
SELECT CI.FECHA_CITA, COUNT(*) AS NUMERO_CITAS
FROM CITAS CI LEFT JOIN PAGOS P ON CI.ID_CLIENTE = P.ID_CLIENTE AND CI.ID_MASCOTA = P.ID_MASCOTA AND CI.FECHA_CITA = P.FECHA_CITA
WHERE P.ID_CLIENTE IS NULL;

--6.Número de mascotas por especie.
SELECT ESPECIE, COUNT(*) AS NUMERO_MASCOTAS
FROM MASCOTAS
GROUP BY ESPECIE

--7.Número de mascotas por cliente.
SELECT ID_CLIENTE, COUNT(*) AS NUMERO_MASCOTAS
FROM MASCOTAS
GROUP BY ID_CLIENTE;

--8.Número de citas por cliente.
SELECT ID_CLIENTE, COUNT(*) AS NUMERO_CITAS 
FROM CITAS
GROUP BY ID_CLIENTE;

--9.Número de citas por mascota.
SELECT ID_MASCOTA, COUNT(*) AS NUMERO_CITAS 
FROM CITAS
GROUP BY ID_MASCOTA;

--10.Número de atenciones por cita.
SELECT FECHA_CITA, COUNT(*) AS NUMERO_ANTENCIONES
FROM ATENCIONES
GROUP BY FECHA_CITA;

--11.Clientes que tienen más de una mascota.
SELECT ID_CLIENTE, COUNT(ID_MASCOTA) AS NUMERO_MASCOTA
FROM MASCOTAS
GROUP BY ID_CLIENTE HAVING COUNT(ID_MASCOTA) >1;

--12.Mascotas que han tenido más de una cita.
SELECT ID_CLIENTE, ID_MASCOTA, COUNT(FECHA_CITA) AS NUMERO_CITAS
FROM CITAS
GROUP BY ID_CLIENTE, ID_MASCOTA HAVING COUNT(FECHA_CITA) > 1;

--13.Fechas de cita en las que hubo más de una atención.
SELECT FECHA_CITA, COUNT(*) AS NUMERO_ANTENCIONES
FROM ATENCIONES
GROUP BY FECHA_CITA HAVING COUNT(*) > 1;

--14.Clientes cuyo importe total pagado supera los 50 €.
SELECT C.ID_CLIENTE, C.NOMBRE, SUM(P.IMPORTE) AS IMPORTE_TOTAL
FROM CLIENTES C JOIN PAGOS P ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.ID_CLIENTE, C.NOMBRE HAVING SUM(P.IMPORTE) > 50;

--15.Veterinarios que han atendido más de una cita.
SELECT P.ID_PERSONAL, P.NOMBRE,
       COUNT(DISTINCT A.ID_CLIENTE || '-' || A.ID_MASCOTA
             || '-' || A.FECHA_CITA) AS NUMERO_CITAS
FROM PERSONAL P
JOIN ATENCIONES A ON P.ID_PERSONAL = A.ID_PERSONAL
WHERE P.ROL = 'Veterinario'
GROUP BY P.ID_PERSONAL, P.NOMBRE
HAVING COUNT(DISTINCT A.ID_CLIENTE || '-' || A.ID_MASCOTA
             || '-' || A.FECHA_CITA) > 1;

--16.Importe total cobrado por la clínica.
SELECT SUM(IMPORTE) AS IMPORTE_TOTAL
FROM PAGOS;

--17.Importe medio de las citas pagadas.
SELECT AVG(IMPORTE) AS IMPORTE_MEDIO
FROM PAGOS;

--18.Importe máximo y mínimo de una cita.
SELECT MAX(IMPORTE) AS MAX_IMPORTE, MIN(IMPORTE) AS MIN_IMPORTE
FROM PAGOS;

--19.Importe total pagado por cliente.
SELECT C.ID_CLIENTE, C.NOMBRE, SUM(P.IMPORTE) AS IMPORTE_TOTAL
FROM CLIENTES C JOIN PAGOS P ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.ID_CLIENTE, C.NOMBRE;

--20.Importe total pagado por mascota.
SELECT C.NOMBRE, M.NOMBRE, SUM(IMPORTE) AS IMPORTE_TOTAL
FROM CLIENTES C JOIN PAGOS P ON C.ID_CLIENTE = P.ID_CLIENTE
JOIN MASCOTAS M ON C.ID_CLIENTE = M.ID_MASCOTA
GROUP BY C.NOMBRE, M.NOMBRE;

SELECT C.ID_CLIENTE, C.NOMBRE AS CLIENTE,
       M.ID_MASCOTA, M.NOMBRE AS MASCOTA,
       SUM(P.IMPORTE) AS IMPORTE_TOTAL
FROM CLIENTES C
JOIN PAGOS P    ON C.ID_CLIENTE = P.ID_CLIENTE
JOIN MASCOTAS M ON P.ID_CLIENTE = M.ID_CLIENTE
               AND P.ID_MASCOTA = M.ID_MASCOTA
GROUP BY C.ID_CLIENTE, C.NOMBRE,
         M.ID_MASCOTA, M.NOMBRE;

--21.Listar todos los nombres de personas (clientes + personal) sin repetir.
SELECT NOMBRE
FROM CLIENTES
UNION
SELECT NOMBRE
FROM PERSONAL;

--22.Lo mismo, pero permitiendo repetidos.
SELECT NOMBRE
FROM CLIENTES
UNION ALL
SELECT NOMBRE
FROM PERSONAL;

--23.Clientes que también aparecen como personal
--(ahora no hay, pero sirve para entender el operador).
SELECT NOMBRE
FROM CLIENTES
INTERSECT
SELECT NOMBRE
FROM PERSONAL;

--24.Clientes que no tienen ninguna cita.
SELECT ID_CLIENTE
FROM CLIENTES
MINUS
SELECT ID_CLIENTE
FROM CITAS;

--25.Mascotas que no tienen pago asociado. 
--¿Podrías hacer la consulta de tal forma que supiéramos el nombre de la mascota y de su cliente?
SELECT C.NOMBRE  AS CLIENTE,
       M.NOMBRE  AS MASCOTA,
       M.ESPECIE
FROM MASCOTAS M
JOIN CLIENTES C
  ON M.ID_CLIENTE = C.ID_CLIENTE
LEFT JOIN CITAS CI
  ON M.ID_CLIENTE = CI.ID_CLIENTE
 AND M.ID_MASCOTA = CI.ID_MASCOTA
LEFT JOIN PAGOS P
  ON CI.ID_CLIENTE = P.ID_CLIENTE
 AND CI.ID_MASCOTA = P.ID_MASCOTA
 AND CI.FECHA_CITA = P.FECHA_CITA
WHERE CI.ID_MASCOTA IS NULL
   OR P.ID_CLIENTE  IS NULL;

--26.Para cada cliente, mostrar:
--número de mascotas
--número de citas
--importe total pagado
SELECT
    C.ID_CLIENTE,
    C.NOMBRE,
    (SELECT COUNT(*)
     FROM MASCOTAS M
     WHERE M.ID_CLIENTE = C.ID_CLIENTE)       AS NUM_MASCOTAS,
    (SELECT COUNT(*)
     FROM CITAS CI
     WHERE CI.ID_CLIENTE = C.ID_CLIENTE)      AS NUM_CITAS,
    (SELECT NVL(SUM(P.IMPORTE), 0)
     FROM PAGOS P
     WHERE P.ID_CLIENTE = C.ID_CLIENTE)       AS IMPORTE_TOTAL
FROM CLIENTES C
ORDER BY C.ID_CLIENTE;

--27.Mostrar la mascota con mayor gasto acumulado.
SELECT M.NOMBRE
FROM MASCOTAS M JOIN PAGOS P ON M.ID_CLIENTE = P.ID_CLIENTE AND M.ID_MASCOTA = P.ID_MASCOTA
GROUP BY M.NOMBRE HAVING SUM(IMPORTE) = (SELECT MAX(SUM(IMPORTE)) 
                                        FROM PAGOS 
                                        GROUP BY ID_CLIENTE, ID_MASCOTA);

--28.Mostrar el cliente con más citas.
SELECT CLI.NOMBRE
FROM CITAS C JOIN CLIENTES CLI ON C.ID_CLIENTE = CLI.ID_CLIENTE
GROUP BY CLI.NOMBRE 
HAVING COUNT(*) = (
    SELECT MAX(CONT(*))
    FROM CITAS
    GROUP BY ID_CLIENTE
);

--29.Mostrar qué veterinario ha realizado más atenciones.
SELECT P.NOMBRE
FROM PERSONAL P JOIN ATENCIONES A ON P.ID_CLIENTE = A.ID_CLIENTE
GROUP BY P.NOMBRE
HAVING COUNT(*) = (
    SELECT MAX(CONT(*))
    FROM ATENCIONES
    GROUP BY ID_PERSONAL
);

