/*
1Mostrar todas las mascotas con el nombre de su dueño
*/
SELECT M.NOMBRE AS NOMBRE_MASCOTA, C.NOMBRE AS NOMBRE_DUEÑO
FROM MASCOTAS M JOIN CLIENTES C ON M.ID_CLIENTE = C.ID_CLIENTE;

--Listar las citas indicando nombre de la mascota y del cliente
SELECT M.NOMBRE AS NOMBRE_MASCOTA, C.NOMBRE AS NOMBRE_DUEÑO, CI.FECHA_CITA
FROM MASCOTAS M JOIN CLIENTES C ON M.ID_CLIENTE = C.ID_CLIENTE
JOIN CITAS CI ON M.ID_CLIENTE = CI.ID_CLIENTE AND M.ID_MASCOTA = CI.ID_MASCOTA;

--Mostrar el personal que trabaja en la clínica
SELECT *
FROM PERSONAL;

--Mostrar las citas de una mascota concreta (Luna)
SELECT M.NOMBRE AS NOMBRE_MASCOTA, CI.FECHA_CITA
FROM MASCOTAS M JOIN CITAS CI ON M.ID_CLIENTE = CI.ID_CLIENTE AND M.ID_MASCOTA = CI.ID_MASCOTA
WHERE UPPER(M.NOMBRE) LIKE '%LUNA%'; 

--Mostrar las citas con su diagnóstico (si lo tienen)
SELECT CI.FECHA_CITA, D.DESCRIPCION
FROM CITAS CI LEFT JOIN DIAGNOSTICOS D ON CI.ID_CLIENTE = D.ID_CLIENTE AND CI.ID_MASCOTA = D.ID_MASCOTA AND CI.FECHA_CITA = D.FECHA_CITA;

--Mostrar las atenciones indicando quién atendió a cada mascota
SELECT ID_PERSONAL, ID_MASCOTA, OBSERVACIONES
FROM ATENCIONES;

--Mostrar las recomendaciones dadas en cada cita
SELECT CI.FECHA_CITA, R.TEXTO
FROM CITAS CI JOIN RECOMENDACIONES R ON CI.ID_CLIENTE = R.ID_CLIENTE AND CI.ID_MASCOTA = R.ID_MASCOTA AND CI.FECHA_CITA = R.FECHA_CITA;

--Mascotas que han tenido al menos una cita
SELECT ID_MASCOTA, COUNT(*)
FROM CITAS
GROUP BY ID_MASCOTA HAVING COUNT(*) >= 1;

--Clientes que han traído alguna mascota a consulta
SELECT DISTINCT C.ID_CLIENTE, C.NOMBRE
FROM CLIENTES C
JOIN MASCOTAS M  ON C.ID_CLIENTE  = M.ID_CLIENTE
JOIN CITAS CI    ON M.ID_CLIENTE  = CI.ID_CLIENTE
               AND M.ID_MASCOTA   = CI.ID_MASCOTA;

SELECT *
FROM CLIENTES C
WHERE EXISTS(SELECT *
            FROM CITAS CI
            WHERE C.ID_CLIENTE = CI.ID_CLIENTE);

--Citas atendidas por el veterinario Dr.Morales
SELECT FECHA_CITA, ID_PERSONAL
FROM ATENCIONES
WHERE ID_PERSONAL = (SELECT ID_PERSONAL
                    FROM PERSONAL
                    WHERE UPPER(NOMBRE) LIKE '%DR.MORALES%' )

--Mascotas sin ninguna cita y sus dueños
SELECT M.NOMBRE AS NOMBRE_MASCOTA, C.NOMBRE AS NOMBRE_DUEÑO
FROM MASCOTAS M JOIN CLIENTES C ON M.ID_CLIENTE = C.ID_CLIENTE
LEFT JOIN CITAS CI ON M.ID_MASCOTA = CI.ID_MASCOTA AND M.ID_CLIENTE = CI.ID_CLIENTE
WHERE CI.ID_MASCOTA IS NULL;

--Citas sin diagnóstico
SELECT CI.ID_CLIENTE, CI.ID_MASCOTA, CI.FECHA_CITA, CI.MOTIVO
FROM CITAS CI
WHERE NOT EXISTS (
    SELECT 1 FROM DIAGNOSTICOS D
    WHERE D.ID_CLIENTE = CI.ID_CLIENTE
      AND D.ID_MASCOTA = CI.ID_MASCOTA
      AND D.FECHA_CITA = CI.FECHA_CITA
);

SELECT CI.ID_CLIENTE, CI.ID_MASCOTA, CI.FECHA_CITA, CI.MOTIVO
FROM CITAS CI
LEFT JOIN DIAGNOSTICOS D
  ON CI.ID_CLIENTE = D.ID_CLIENTE
 AND CI.ID_MASCOTA = D.ID_MASCOTA
 AND CI.FECHA_CITA = D.FECHA_CITA
WHERE D.ID_CLIENTE IS NULL;

--Citas sin pago registrado
SELECT *
FROM CITAS CI
WHERE NOT EXISTS (SELECT 1
                FROM PAGOS P
                WHERE CI.ID_CLIENTE = P.ID_CLIENTE
                AND CI.ID_MASCOTA = P.ID_MASCOTA
                AND CI.FECHA_CITA = P.FECHA_CITA);

SELECT CI.FECHA_CITA
FROM CITAS CI LEFT JOIN PAGOS P ON CI.ID_CLIENTE = P.ID_CLIENTE AND CI.ID_MASCOTA = P.ID_MASCOTA AND CI.FECHA_CITA = P.FECHA_CITA
WHERE ID_CLIENTE IS NULL;

--Citas realizadas en el mismo mes que el mes de nacimiento de la mascota atendida
SELECT CI.FECHA_CITA, M.FECHA_NAC AS FECHA_NACIMIENTO
FROM MASCOTAS M JOIN CITAS CI ON M.ID_CLIENTE = CI.ID_CLIENTE AND M.ID_MASCOTA = CI.ID_MASCOTA
WHERE EXTRACT(MONTH FROM FECHA_CITA) = EXTRACT(MONTH FROM FECHA_NAC);

--Citas posteriores al 18 de febrero de 2024
SELECT FECHA_CITA
FROM CITAS
WHERE FECHA_CITA > DATE '2024-02-18';

--Mascotas nacidas antes del año 2020
SELECT NOMBRE, FECHA_NAC
FROM MASCOTAS
WHERE FECHA_NAC < DATE '2020-01-01';

SELECT NOMBRE, FECHA_NAC
FROM MASCOTAS
WHERE EXTRACT(YEAR FROM FECHA_NAC) < 2020;

