CREATE OR REPLACE TRIGGER controlPagos
BEFORE UPDATE ON PAGOS
FOR EACH ROW
BEGIN
    IF :NEW.FECHA_PAGO > :NEW.FECHA_CITA THEN
        RAISE_APPLICATION_ERROR(-20003,'No se puede marcar un pago con fecha anterior a la cita.');
    END IF;
END;

--PRUEBA
UPDATE PAGOS
SET FECHA_PAGO = DATE '2026-12-31'
WHERE ID_CLIENTE = 2 AND ID_MASCOTA = 1 AND FECHA_CITA = DATE '2027-01-01';