CREATE OR REPLACE TRIGGER generadorPagos
AFTER INSERT ON CITAS
FOR EACH ROW
DECLARE
    nPagos NUMBER := 0;
    existePagos EXCEPTION;
BEGIN
    SELECT COUNT(*)
    INTO nPagos
    FROM PAGOS
    WHERE ID_CLIENTE = :NEW.ID_CLIENTE
    AND ID_MASCOTA = :NEW.ID_MASCOTA
    AND FECHA_CITA = :NEW.FECHA_CITA;

    IF nPagos <> 0 THEN
        RAISE existePagos;
    END IF;

    INSERT INTO PAGOS (ID_CLIENTE, ID_MASCOTA, FECHA_CITA, IMPORTE, FECHA_PAGO)
    VALUES (:NEW.ID_CLIENTE,:NEW.ID_MASCOTA,:NEW.FECHA_CITA,50, NULL);

EXCEPTION
    WHEN existePagos THEN
        DBMS_OUTPUT.PUT_LINE('Este pago ya existe');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('codigo error: ' || SQLCODE || ', mensaje error: ' || SQLERRM);
END;

--PRUEBA
INSERT INTO CITAS
VALUES (2, 1, DATE '2027-01-01', 'Revisión Futura');

SELECT *
FROM PAGOS
WHERE FECHA_CITA = DATE '2027-01-01';