CREATE TABLE LOG_CLIENTES (
    ID_LOG NUMBER GENERATED ALWAYS AS IDENTITY,
    MENSAJE VARCHAR2(200),
    FECHA DATE
);

CREATE OR REPLACE TRIGGER auditoriaSimple
AFTER UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
    IF :OLD.TELEFONO <> :NEW.TELEFONO THEN
        INSERT INTO LOG_CLIENTES(MENSAJE,FECHA)
        VALUES ('El telefono del cliente: ' || :OLD.NOMBRE || ' ha cambiado de ' || :OLD.TELEFONO
        || ' a ' || :NEW.TELEFONO, SYSDATE);
    END IF;
END;

--PRUEBA--
UPDATE CLIENTES
SET TELEFONO = '699000111'
WHERE ID_CLIENTE = 1;

SELECT * FROM LOG_CLIENTES;