CREATE OR REPLACE TRIGGER validacionFechas
BEFORE INSERT ON CITAS
FOR EACH ROW
BEGIN
    IF :NEW.FECHA_CITA < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20001,'No se puede insertar una cita en una fecha pasada.');
    END IF;
END;

--PRUEBA
INSERT INTO CITAS (ID_CLIENTE, ID_MASCOTA,FECHA_CITA)
VALUES (1,1,DATE'2024-01-15');