DROP TABLE ESPECTACULOS CASCADE CONSTRAINTS;
DROP TABLE PRECIOS_ESPECTACULOS CASCADE CONSTRAINTS;
DROP TABLE RECINTOS CASCADE CONSTRAINTS;
DROP TABLE ZONAS_RECINTOS CASCADE CONSTRAINTS;
DROP TABLE ASIENTOS CASCADE CONSTRAINTS;
DROP TABLE REPRESENTACIONES CASCADE CONSTRAINTS;
DROP TABLE ENTRADAS CASCADE CONSTRAINTS;
DROP TABLE ESPECTADORES CASCADE CONSTRAINTS;

CREATE TABLE ESPECTACULOS (
    COD_ESPECTACULO VARCHAR2(4),
    NOMBRE VARCHAR2(200),
    TIPO VARCHAR2(100),
    FECHA_INICIAL DATE,
    FECHA_FINAL DATE,
    INTERPRETE VARCHAR2(100),
    COD_RECINTO VARCHAR2(4),
    CONSTRAINT ESPECTACULOS_COD_PK PRIMARY KEY (COD_ESPECTACULO),
    CONSTRAINT ESPECTACULOS_FECHAS_CH CHECK(FECHA_FINAL > FECHA_INICIAL)
);

CREATE TABLE PRECIOS_ESPECTACULOS(
    COD_ESPECTACULO VARCHAR2(4),
    COD_RECINTO VARCHAR2(4),
    ZONA VARCHAR2(4),
    PRECIO NUMBER(5,2),
    CONSTRAINT PRECIOESPEC_COD_PK PRIMARY KEY (COD_ESPECTACULO, COD_RECINTO, ZONA)
);

CREATE TABLE RECINTOS (
    COD_RECINTO VARCHAR2(4), 
    NOMBRE VARCHAR2(100), 
    DIRECCION VARCHAR2(200), 
    CIUDAD VARCHAR2(200), 
    TELEFONO NUMBER(9), 
    HORARIO VARCHAR2(50),
    CONSTRAINT RECINTOS_COD_PK PRIMARY KEY (COD_RECINTO)
);

ALTER TABLE ESPECTACULOS
    ADD CONSTRAINT ESPECT_RECINTO_FK FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS;

CREATE TABLE ZONAS_RECINTOS(
    COD_RECINTO VARCHAR2(4), 
    ZONA VARCHAR2(4), 
    CAPACIDAD NUMBER(4),
    CONSTRAINT ZONASRECINTOS_COD_PK PRIMARY KEY(COD_RECINTO, ZONA),
    CONSTRAINT ZONASRECINTOS_RECINTO_FK FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS
);
/*foreign key de la tabla precios_espectaculos*/
/*
ALTER TABLE PRECIOS_ESPECTACULOS
    ADD CONSTRAINT PRECIOESPEC_ESPECT_FK FOREIGN KEY (COD_ESPECTACULO)
    REFERENCES ESPECTACULOS;

ALTER TABLE PRECIOS_ESPECTACULOS
    ADD CONSTRAINT PRECIOESPEC_ZONASREC_FK FOREIGN KEY (COD_RECINTO, ZONA)
    REFERENCES ZONAS_RECINTOS;
*/
ALTER TABLE PRECIOS_ESPECTACULOS
    ADD (
        CONSTRAINT PRECIOESPEC_ESPECT_FK 
            FOREIGN KEY (COD_ESPECTACULO) 
            REFERENCES ESPECTACULOS,
        CONSTRAINT PRECIOESPEC_ZONASREC_FK 
            FOREIGN KEY (COD_RECINTO, ZONA) 
            REFERENCES ZONAS_RECINTOS
    );



CREATE TABLE ASIENTOS (
    COD_RECINTO VARCHAR2(4),
    ZONA VARCHAR2(4),
    FILA NUMBER(2),
    NUMERO NUMBER(2),
    CONSTRAINT ASIENTOS_CLAVES_PK PRIMARY KEY (COD_RECINTO, ZONA, FILA, NUMERO),
    /* redundante CONSTRAINT ASIENTOS_RECINTO_FK FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS,*/
    CONSTRAINT ASIENTOS_RECINTOZONA_FK FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS
);

CREATE TABLE REPRESENTACIONES (
    COD_ESPECTACULO VARCHAR2(4),
    FECHA DATE,
    HORA DATE,
    CONSTRAINT REPRES_CLAVES_PK PRIMARY KEY (COD_ESPECTACULO, FECHA, HORA),
    CONSTRAINT REPRES_ESPECT_FK FOREIGN KEY(COD_ESPECTACULO) REFERENCES ESPECTACULOS
);

CREATE TABLE ENTRADAS(
    COD_ESPECTACULO VARCHAR2(4),
    FECHA DATE,
    HORA DATE,
    COD_RECINTO VARCHAR2(4),
    FILA NUMBER(2),
    NUMERO NUMBER,
    ZONA VARCHAR2(4),
    DNI_CLIENTE VARCHAR2(9),
    CONSTRAINT ENTRADAS_CLAVE_PK PRIMARY KEY(COD_ESPECTACULO, FECHA, HORA, COD_RECINTO, FILA, NUMERO, ZONA),
    /* redundante CONSTRAINT ENTRADAS_ESPECT_FK FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS,*/
    CONSTRAINT ENTRADAS_REPRESE_FK FOREIGN KEY (COD_ESPECTACULO, FECHA, HORA) REFERENCES REPRESENTACIONES,
    /* redundante CONSTRAINT ENTRADAS_RECINTO_FK FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS,*/
    /* redundante CONSTRAINT ENTRADAS_RECINTOZONAS_FK FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS,*/
    CONSTRAINT ENTRADAS_ASIENTOS_FK FOREIGN KEY (COD_RECINTO, ZONA, FILA, NUMERO) REFERENCES ASIENTOS
);

CREATE TABLE ESPECTADORES(
    DNI_CLIENTE VARCHAR2(9),
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(200),
    TELEFONO NUMBER(9),
    CIUDAD VARCHAR2(200),
    NTARJETA VARCHAR2(12),
    CONSTRAINT ESPECTADORES_CLAVE_PK PRIMARY KEY (DNI_CLIENTE)
);