DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL_LABORAL CASCADE CONSTRAINTS;
DROP TABLE ESTUDIOS CASCADE CONSTRAINTS;
DROP TABLE UNIVERSIDADES CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL_SALARIALS CASCADE CONSTRAINTS;
DROP TABLE TRABAJOS CASCADE CONSTRAINTS;

CREATE TABLE EMPLEADOS (
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(10) NOT NULL,
    APELLIDO1 VARCHAR2(15) NOT NULL,
    APELLIDO2 VARCHAR2(15),
    DIRECC1 VARCHAR2(25),
    DIRECC2 VARCHAR2(20),
    CIUDAD VARCHAR2(20),
    PROVINCIA VARCHAR2(20),
    COD_POSTAL VARCHAR2(5),
    FECHA_NAC DATE,
    SEXO CHAR(1),
    CONSTRAINT EMPLEADOS_COD_PK PRIMARY KEY (DNI),
    CONSTRAINT EMPLEADOS_SEXO_CH CHECK (SEXO IN ('H', 'M'))
);

CREATE TABLE DEPARTAMENTOS(
    DPTO_COD NUMBER(5),
    NOMBRE_DPTO VARCHAR2(30) NOT NULL UNIQUE,
    DPTO_PADRE NUMBER(5),
    PRESUPUESTO NUMBER(7,2) NOT NULL,
    PRES_ACTUAL NUMBER(7,2),
    CONSTRAINT DEPARTAMENTOS_COD_PK PRIMARY KEY (DPTO_COD),
    CONSTRAINT DEPARTAMENTOS_PADRE_FK FOREIGN KEY(DPTO_PADRE) REFERENCES DEPARTAMENTOS
);

CREATE TABLE ESTUDIOS (
    EMPLEADO_DNI VARCHAR2(9),
    ESPECIALIDAD VARCHAR2(20),
    UNIVERSIDAD NUMBER(5),
    ANIO NUMBER(4),
    GRADO VARCHAR2(30),
    CONSTRAINT ESTUDIOS_CLAVE_PK PRIMARY KEY (EMPLEADO_DNI, ESPECIALIDAD),
    CONSTRAINT ESTUDIOS_EMPLEADO_FK FOREIGN KEY(EMPLEADO_DNI) REFERENCES EMPLEADOS
);/*FALTA FOREIGN KEY A UNIVERSIDADES*/

CREATE TABLE HISTORIAL_LABORAL(
    EMPLEADO_DNI VARCHAR2(9),
    TRABAJO_COD NUMBER(5),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DPTO_COD NUMBER(5),
    SUPERVISOR_DNI VARCHAR2(9),
    /*CONSTRAINT HISTOLAB_EMPLTRAB_UQ UNIQUE (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO),
    CUBIERTO CON LA CLAVE PRIMARIA*/
    CONSTRAINT HISTOLAB_CLAVE_PK PRIMARY KEY(EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO),
    CONSTRAINT HISTOLAB_EMPLEADO_FK FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS,
    CONSTRAINT HISTOLAB_DEPARTAMENTO_FK FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS,
    CONSTRAINT HISTOLAB_FECHAS_CH CHECK (FECHA_FIN > FECHA_INICIO),
    CONSTRAINT HISTOLAB_SUPERVISOR_FK FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS
);/*FALTA FOREIGN KEY A TRABAJOS*/

CREATE TABLE UNIVERSIDADES (
    UNIV_COD NUMBER(5),
    NOMBRE_UNIV VARCHAR2(25) NOT NULL,
    CIUDAD VARCHAR2(20),
    MUNICIPIO VARCHAR2(2),
    COD_POSTAL VARCHAR2(5),
    CONSTRAINT UNIVERSIDADES_CLAVE_PK PRIMARY KEY(UNIV_COD)
);

ALTER TABLE ESTUDIOS
    ADD CONSTRAINT ESTUDIOS_UNIV_FK FOREIGN KEY (UNIVERSIDAD) REFERENCES UNIVERSIDADES;

CREATE TABLE HISTORIAL_SALARIAL(
    EMPLEADO_DNI VARCHAR2(9),
    SALARIO NUMBER(7,2) NOT NULL,
    FECHA_COMIENZO DATE,
    FECHA_FIN DATE,
    /*CONSTRAINT HISTOSAL_EMPLSAL_UQ UNIQUE (EMPLEADO_DNI, SALARIO, FECHA_COMIENZO),
    CUBIERTO CON LA CLAVE PRIMARIA*/
    CONSTRAINT HISTOSALA_PK PRIMARY KEY(EMPLEADO_DNI, SALARIO, FECHA_COMIENZO),
    CONSTRAINT HISTOSALA_EMPLEADO_FK FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS,
    CONSTRAINT HISTOSALA_FECHAS_CH CHECK (FECHA_FIN > FECHA_COMIENZO)
);

CREATE TABLE TRABAJOS (
    TRABAJO_COD NUMBER(5),
    NOMBRE_TRAB VARCHAR2(20) NOT NULL UNIQUE,
    SALARIO_MIN NUMBER(2) NOT NULL,
    SALARIO_MAX NUMBER(2) NOT NULL,
    CONSTRAINT TRABAJOS_PK PRIMARY KEY(TRABAJO_COD)
);

ALTER TABLE HISTORIAL_LABORAL
    ADD CONSTRAINT HISTOLAB_TRABAJO_FK FOREIGN KEY (TRABAJO_COD) REFERENCES TRABAJOS;

/*OPERACIONES PEDIDAS*/
/*    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(10) NOT NULL,
    APELLIDO1 VARCHAR2(15) NOT NULL,
    APELLIDO2 VARCHAR2(15),
    DIRECC1 VARCHAR2(25),
    DIRECC2 VARCHAR2(20),
    CIUDAD VARCHAR2(20),
    PROVINCIA VARCHAR2(20),
    COD_POSTAL VARCHAR2(5),
    FECHA_NAC DATE,
    SEXO CHAR(1),*/
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, SEXO)
VALUES ('Sergio', 'Palma', 'Entrena', '111222', 'p');
/*restricción violada*/
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, SEXO)
VALUES ('Sergio', 'Palma', 'Entrena', '111222', 'H');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDO1, APELLIDO2, DNI)
VALUES ('Lucía', 'Ortega', 'Plus', '222333');

/*
EMPLEADO_DNI VARCHAR2(9),
    TRABAJO_COD NUMBER(5),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DPTO_COD NUMBER(5),
    SUPERVISOR_DNI VARCHAR2(9),
*/
INSERT INTO HISTORIAL_LABORAL (EMPLEADO_DNI, FECHA_INICIO, DEPTO_COD)
VALUES ('111222', TO_DATE('16-06-1996', 'DD-MM-YYYY'), 222333);

/*
¿Qué ocurre si se modifica esta última fila de historial_laboral asignándole al
empleado 111222 un supervisor que no existe en la tabla de empleados?
Para probarlo introduzco información en DEPARTAMENTOS
Tengo que insertar también en TRABAJOS
*/
/*
    DPTO_COD NUMBER(5),
    NOMBRE_DPTO VARCHAR2(30) NOT NULL UNIQUE,
    DPTO_PADRE NUMBER(5),
    PRESUPUESTO NUMBER(7,2) NOT NULL,
    PRES_ACTUAL NUMBER(7,2)
*/

INSERT INTO DEPARTAMENTOS (DPTO_COD, NOMBRE_DPTO, PRESUPUESTO)
VALUES (11111, 'DESARROLLO', 20500);

/*
TRABAJO_COD NUMBER(5),
    NOMBRE_TRAB VARCHAR2(20) NOT NULL UNIQUE,
    SALARIO_MIN NUMBER(2) NOT NULL,
    SALARIO_MAX NUMBER(2) NOT NULL,
*/

INSERT INTO TRABAJOS (TRABAJO_COD, NOMBRE_TRAB, SALARIO_MIN, SALARIO_MAX)
VALUES (11111,'FRONTEND', 20, 50);


INSERT INTO HISTORIAL_LABORAL (TRABAJO_COD, EMPLEADO_DNI, FECHA_INICIO, DPTO_COD, SUPERVISOR_DNI)
VALUES (11111, '111222', TO_DATE('16-06-1996', 'DD-MM-YYYY'), 11111, 222333);

INSERT INTO HISTORIAL_LABORAL (TRABAJO_COD, EMPLEADO_DNI, FECHA_INICIO, DPTO_COD, SUPERVISOR_DNI)
VALUES (11111, '111222', TO_DATE('16-06-1996', 'DD-MM-YYYY'), 11111, 222555);

/*4. Borre una universidad de la tabla de UNIVERSIDADES ¿Qué le sucede a la
restricción de clave ajena de la tabla ESTUDIOS? Altere la definición de la tabla
para que se mantenga la restricción aunque se borre una universidad.*/

/*PRIMERO INSERTO PARA TENER
UNIV_COD NUMBER(5),
    NOMBRE_UNIV VARCHAR2(25) NOT NULL,
    CIUDAD VARCHAR2(20),
    MUNICIPIO VARCHAR2(2),
    COD_POSTAL VARCHAR2(5),*/

INSERT INTO UNIVERSIDADES VALUES (11111, 'UAH', 'ALCALÁ DE HENARES','ALCALÁ DE HENARES', '28805');

ALTER TABLE ESTUDIOS
DROP CONSTRAINT ESTUDIOS_UNIV_FK;

ALTER TABLE ESTUDIOS
ADD CONSTRAINT ESTUDIOS_UNIV_FK FOREIGN KEY (UNIVERSIDAD)
REFERENCES UNIVERSIDADES(UNIV_COD)
ON DELETE SET NULL;

/*5. Añada una restricción que obligue a que las personas que hayan introducido la
CIUDAD tengan que tener el campo COD_POSTAL a NOT NULL. ¿Qué ocurre con
las filas ya introducidas?*/
ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_CP_CH
CHECK (CIUDAD IS NULL OR COD_POSTAL IS NOT NULL);
/*
Si CIUDAD es NULL → la expresión CIUDAD IS NULL es verdadera → condición cumplida (no se pidió código postal).

Si CIUDAD no es NULL → entonces debe cumplirse COD_POSTAL IS NOT NULL.
¿Qué ocurre con las filas ya introducidas?

Si alguna fila tiene CIUDAD NOT NULL y COD_POSTAL NULL, el ALTER TABLE fallará.

Solo se añadirá si todos los datos actuales cumplen la condición.*/

INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO1, CIUDAD)
VALUES ('666458X','ANA', 'SÁNCHEZ', 'ALCALÁ DE HENARES');


/*6. Añada un nuevo atributo VALORACIÓN en la tabla de EMPLEADOS que indique
de 1 a 10 la valoración que obtuvo el empleado en su entrevista de trabajo al iniciar
su andadura en la empresa. Ponga el valor por defecto 5 para ese campo.*/
ALTER TABLE EMPLEADOS
ADD VALORACION NUMBER(2)
DEFAULT 5
CHECK (VALORACION BETWEEN 1 AND 10);


/*7. Elimine la restricción de que el atributo NOMBRE de la tabla EMPLEADOS no
puede ser nulo.*/
SELECT UC.CONSTRAINT_NAME, UC.TABLE_NAME, UC.CONSTRAINT_TYPE, UCC.COLUMN_NAME 
FROM USER_CONSTRAINTS UC JOIN USER_CONS_COLUMNS UCC ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
WHERE UC.TABLE_NAME = 'EMPLEADOS' AND UCC.COLUMN_NAME = 'NOMBRE';

SYS_C008424

ALTER TABLE EMPLEADOS
ALTER TABLE EMPLEADOS
DROP CONSTRAINT SYS_C008424;




/*8. Modificar el tipo de datos de DIREC1 de la tabla EMPLEADOS a cadena de
caracteres de 40 como máximo.*/

ALTER TABLE EMPLEADOS
MODIFY DIRECC1 VARCHAR2(40);


/*9. ¿Podría modificar el tipo de datos del atributo FECHA_NAC de la tabla
EMPLEADOS Y convertirla a tipo cadena?*/

ALTER TABLE EMPLEADOS
MODIFY FECHA_NAC VARCHAR2(20);
Pero se perdería la capacidad de comparar fechas, y no es recomendable en bases reales.

/*10. Cambiar la clave primaria de EMPLEADOS al NOMBRE y los dos APELLIDOS.*/

Pasos:

1.Eliminar la PK actual (sobre DNI)
2.Crear la nueva PK

ALTER TABLE EMPLEADOS
DROP CONSTRAINT EMPLEADOS_COD_PK;

ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_PK
PRIMARY KEY (NOMBRE, APELLIDO1, APELLIDO2);


/*11. Crear una nueva tabla llamada INFORMACIÓN UNIVERSITARIA que tenga el
NOMBRE y los dos APELLIDOS (en un solo atributo) de todos los EMPLEADOS
junto con la UNIVERSIDAD donde estudiaron. Cárguela con los datos
correspondientes.*/

CREATE TABLE INFORMACION_UNIVERSITARIA AS
SELECT 
    e.NOMBRE || ' ' || e.APELLIDO1 || ' ' || e.APELLIDO2 AS NOMBRE_COMPLETO,
    u.NOMBRE_UNIV
FROM EMPLEADOS e
JOIN ESTUDIOS es ON e.DNI = es.EMPLEADO_DNI
JOIN UNIVERSIDADES u ON es.UNIVERSIDAD = u.UNIV_COD;



/*12. Crear una vista llamada NOMBRE_EMPLEADOS con el NOMBRE y los dos
APELLIDOS (en un solo atributo) de todos los EMPLEADOS que son de Málaga.*/

CREATE VIEW NOMBRE_EMPLEADOS AS
SELECT 
    NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2 AS NOMBRE_COMPLETO
FROM EMPLEADOS
WHERE CIUDAD = 'Málaga';


/*13. Crear otra vista llamada INFORMACION_EMPLEADOS con el NOMBRE y los dos
APELLIDOS (en un solo atributo) y EDAD (no fecha de nacimiento) de todos los
EMPLEADOS.*/

CREATE VIEW INFORMACION_EMPLEADOS AS
SELECT 
    NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2 AS NOMBRE_COMPLETO,
    FLOOR((SYSDATE - FECHA_NAC) / 365) AS EDAD
FROM EMPLEADOS;


/*14. Crear otra vista sobre la anterior llamada INFORMACION_ACTUAL que dispone de
toda la información de INFORMACION_EMPLEADOS junto con el SALARIO que
está cobrando en este momento.*/

CREATE VIEW INFORMACION_ACTUAL AS
SELECT 
    ie.NOMBRE_COMPLETO,
    ie.EDAD,
    hs.SALARIO
FROM INFORMACION_EMPLEADOS ie
JOIN EMPLEADOS e ON ie.NOMBRE_COMPLETO =
       e.NOMBRE || ' ' || e.APELLIDO1 || ' ' || e.APELLIDO2
JOIN HISTORIAL_SALARIAL hs ON e.DNI = hs.EMPLEADO_DNI
WHERE hs.FECHA_FIN IS NULL;


/*15. Borrar todas las tablas. ¿Hay que tener en cuenta las claves ajenas a la hora de
borrar las tablas?*/






