DROP TABLE PUB CASCADE CONSTRAINTS;
DROP TABLE TITULAR CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE EXISTENCIAS CASCADE CONSTRAINTS;
DROP TABLE LOCALIDAD CASCADE CONSTRAINTS;
DROP TABLE PUB_EMPLEADO CASCADE CONSTRAINTS;

CREATE TABLE PUB(
    COD_PUB VARCHAR2(3) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    LICENCIA_FICAL VARCHAR2(100) NOT NULL,
    DOMICILIO VARCHAR2(100),
    FECHA_APERTURA DATE NOT NULL,
    HORARIO VARCHAR2(4) NOT NULL,
    COD_LOCALIDAD VARCHAR2(3) NOT NULL,
    CONSTRAINT PUB_COD_PK PRIMARY KEY (COD_PUB),
    CONSTRAINT HORARIO CHECK (HORARIO IN ('HOR1', 'HOR2', 'HOR3'))
);

CREATE TABLE TITULAR(
    DNI_TITULAR VARCHAR2(9) CONSTRAINT TIT_COD_PK PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DOMICILIO VARCHAR2(200),
    COD_PUB VARCHAR2(3) REFERENCES PUB
);

CREATE TABLE EMPLEADO(
    DNI_EMPLEADO VARCHAR2(9) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DOMICILIO VARCHAR2(200),
    CONSTRAINT EMP_DNI_PK PRIMARY KEY (DNI_EMPLEADO)
);

CREATE TABLE EXISTENCIAS (
    COD_ARTICULO VARCHAR2(3) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CANTIDAD NUMBER(5,2) NOT NULL,
    PRECIO NUMBER(5,2) NOT NULL,
    COD_PUB VARCHAR2(3) NOT NULL,
    CONSTRAINT EXI_COD_PK PRIMARY KEY (COD_ARTICULO),
    CONSTRAINT EXI_PRE_CH CHECK (PRECIO > 0),
    CONSTRAINT EXI_PUB_FK FOREIGN KEY (COD_PUB) REFERENCES PUB
);

CREATE TABLE LOCALIDAD (
    COD_LOCALIDAD VARCHAR2(3) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE PUB_EMPLEADO(
    COD_PUB VARCHAR2(3) NOT NULL,
    DNI_EMPLEADO VARCHAR2(9) NOT NULL,
    FUNCION VARCHAR2(20) NOT NULL,
    CONSTRAINT PUEMP_COD_PK PRIMARY KEY (COD_PUB, DNI_EMPLEADO, FUNCION),
    CONSTRAINT PUBEMP_FUNCION_CH CHECK (FUNCION IN ('CAMARERO', 'SEGURIDAD', 'LIMPIEZA')),
    CONSTRAINT PUBEMP_PUB_FK FOREIGN KEY (COD_PUB) REFERENCES PUB,
    CONSTRAINT PUBEMP_EMPLE_FK FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO
);


