--1
SELECT NOMBRE || ' ' || APELLIDOS AS ALUMNOS_REPETIDORES, FECHA_NACIMIENTO
FROM ALUMNOS
WHERE REPETIDOR IN ('S')
ORDER BY FECHA_NACIMIENTO;

--2
SELECT NOMBRE || ' ' || APELLIDOS AS ALUMNOS, DECODE(REPETIDOR, 'S','Es repetidor','N','No es repetidor') AS REPETIDOR, FECHA_NACIMIENTO
FROM ALUMNOS
ORDER BY FECHA_NACIMIENTO;

--3
SELECT A.NOMBRE || ' ' || A.APELLIDOS AS ALUMNOS, CR.CODIGO AS CE, CR.DESCRIPCION, C.NOTA
FROM CALIFICACIONES C JOIN ALUMNOS A ON C.ID_ALUMNO = A.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CR ON C.ID_CE = CR.ID_CE AND C.ID_RA = CR.ID_RA
WHERE C.ID_RA = 1
ORDER BY A.NOMBRE, A.APELLIDOS, CR.CODIGO;

--4
SELECT A.NOMBRE || ' ' || A.APELLIDOS AS ALUMNOS, AVG(C.NOTA) AS NOTA_MEDIA_RA6
FROM ALUMNOS A
JOIN CALIFICACIONES C ON A.ID_ALUMNO = C.ID_ALUMNO
JOIN CRITERIOS_EVALUACION CR ON C.ID_CE = CR.ID_CE AND C.ID_RA = CR.ID_RA
WHERE C.ID_RA = 6 AND C.ID_PRUEBA = 2
GROUP BY A.NOMBRE, A.APELLIDOS;

--5
SELECT DISTINCT RA.CODIGO AS RA, RA.DESCRIPCION AS RA_DESCRIPCION, NVL(P.NOMBRE, 'No existe prueba') AS NOMBRE_PRUEBA, P.TIPO AS TIPO_PRUEBA
FROM RESULTADOS_APRENDIZAJE RA JOIN CALIFICACIONES C ON RA.ID_RA = C.ID_RA
LEFT JOIN PRUEBAS_EVALUACION P ON C.ID_PRUEBA = P.ID_PRUEBA;

--6
SELECT RA.CODIGO AS RA, NVL(C.NOTA, 'No se ha hecho prueba aún') AS PRUEBA
FROM CALIFICACIONES C JOIN CRITERIOS_EVALUACION CR ON C.ID_CE = CR.ID_CE AND C.ID_RA = CR.ID_RA
LEFT JOIN RESULTADOS_APRENDIZAJE RA ON CR.ID_RA = RA.ID_RA
WHERE C.NOTA IS NULL;

SELECT RA.CODIGO AS RA,
CASE
    WHEN PC.ID_PRUEBA IS NULL THEN 'No se ha hecho prueba aún'
    ELSE TO_CHAR(PC.ID_PRUEBA)
END AS PRUEBA
FROM RESULTADOS_APRENDIZAJE RA LEFT JOIN PRUEBAS_CRITERIOS PC ON RA.ID_RA = PC.ID_RA
WHERE PC.ID_PRUEBA IS NULL;

SELECT RA.CODIGO AS RA, 'No se ha hecho prueba aún' AS PRUEBA
FROM RESULTADOS_APRENDIZAJE RA LEFT JOIN PRUEBAS_CRITERIOS PC ON RA.ID_RA = PC.ID_RA
WHERE PC.ID_PRUEBA IS NULL;

--7
SELECT RA.ID_RA AS RA, ROUND(AVG(C.NOTA),2) AS NOTA_MEDIA
FROM CALIFICACIONES C JOIN CRITERIOS_EVALUACION CR ON C.ID_CE = CR.ID_CE AND C.ID_RA = CR.ID_RA
JOIN RESULTADOS_APRENDIZAJE RA ON CR.ID_RA = RA.ID_RA
GROUP BY RA.ID_RA;

SELECT RA.ID_RA AS RA, ROUND(AVG(NOTA),2) AS NOTA_MEDIA
FROM RESULTADOS_APRENDIZAJE RA JOIN CALIFICACIONES C ON RA.ID_RA = C.ID_RA
GROUP BY RA.ID_RA;

--8
SELECT P.ID_PRUEBA, A.NOMBRE || ' ' || A.APELLIDOS AS ALUMNO, MAX(C.NOTA) AS NOTA_MAXIMA, MIN(C.NOTA) AS NOTA_MINIMA
FROM CALIFICACIONES C JOIN ALUMNOS A ON C.ID_ALUMNO = A.ID_ALUMNO
JOIN PRUEBAS_EVALUACION P ON C.ID_PRUEBA = P.ID_PRUEBA
GROUP BY P.ID_PRUEBA,A.NOMBRE, A.APELLIDOS HAVING P.ID_PRUEBA = 4;

--9

--10

--11
SELECT A.NOMBRE || ' ' || A.APELLIDOS AS ALUMNO, TRUNC(MONTHS_BETWEEN(SYSDATE,A.FECHA_NACIMIENTO)/12) || ' años' AS EDAD
FROM ALUMNOS A;

--12

---a
SELECT titulo
FROM libros l JOIN autores a ON l.id_autor = a.id_autor
WHERE a.nombre = 'Gabriel García Márquez';

---b
SELECT fecha_prestamo, fecha_devolucion
FROM prestamos
WHERE fecha_prestamo >= DATE '2024-01-01' AND fecha_prestamo <  DATE '2025-01-01';

--13
CREATE VIEW V_ALUMNOS_APROBADOS_RA
AS
SELECT A.ID_ALUMNO, A.NOMBRE || ' ' || A.APELLIDOS AS ALUMNO, RA.ID_RA AS ID_RA, RA.CODIGO AS RA_CODIGO, C.NOTA
FROM CALIFICACIONES C JOIN ALUMNOS A ON C.ID_ALUMNO = A.ID_ALUMNO
JOIN RESULTADOS_APRENDIZAJE RA ON C.ID_RA = RA.ID_RA
WHERE C.NOTA >5;